# Generated by Django 6.0.6 on 2026-08-24 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateCuttingPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название набора')),
                ('search_name', models.CharField(db_index=True, max_length=120, verbose_name='Ключ поиска')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plate_cutting_presets', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Набор пакетов рубки пластин',
                'verbose_name_plural': 'Наборы пакетов рубки пластин',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PlateCuttingPresetPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_value', models.CharField(max_length=4, verbose_name='Диапазон длины')),
                ('plate_count', models.PositiveIntegerField(verbose_name='Количество пластин')),
                ('hole_count', models.PositiveIntegerField(verbose_name='Количество отверстий')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='plate_cutting.platecuttingpreset', verbose_name='Набор')),
            ],
            options={
                'verbose_name': 'Пакет набора рубки пластин',
                'verbose_name_plural': 'Пакеты наборов рубки пластин',
                'ordering': ['display_order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('preset', 'display_order'), name='unique_plate_cutting_preset_package_order'), models.CheckConstraint(condition=models.Q(('plate_count__gte', 1)), name='plate_cutting_preset_package_plates_positive')],
            },
        ),
    ]
