# Generated by Django 6.0.6 on 2026-08-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_cutting', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='platecuttingpresetpackage',
            constraint=models.CheckConstraint(condition=models.Q(('plate_count__lte', 1000000)), name='plate_cutting_preset_package_plates_within_limit'),
        ),
        migrations.AddConstraint(
            model_name='platecuttingpresetpackage',
            constraint=models.CheckConstraint(condition=models.Q(('hole_count__lte', 1000000)), name='plate_cutting_preset_package_holes_within_limit'),
        ),
    ]
