# Generated by Django 6.0.6 on 2026-08-31 11:01

import django.core.validators
from django.conf import settings
from django.db import migrations, models


NAME_MAX_LENGTH = 120


def normalize_and_deduplicate_names(apps, schema_editor):
    """Prepare every historical row for the normalized-name unique key."""
    Preset = apps.get_model('plate_cutting', 'PlateCuttingPreset')
    rows = list(Preset.objects.order_by('pk').values('pk', 'name'))

    def normalized(value):
        return str(value or '').strip().lower()

    original_keys = {normalized(row['name']) for row in rows}
    reserved = set(original_keys)
    first_name_by_key = {}
    seen = set()

    for row in rows:
        display_name = str(row['name'] or '').strip() or 'Набор'
        key = normalized(display_name)
        if key and key not in seen:
            final_name = display_name[:NAME_MAX_LENGTH]
            final_key = normalized(final_name)
            first_name_by_key[key] = final_name
        else:
            base_name = first_name_by_key.get(key, display_name)
            number = 1
            while True:
                suffix = f'_{number:02d}'
                candidate = f'{base_name[:NAME_MAX_LENGTH - len(suffix)]}{suffix}'
                candidate_key = normalized(candidate)
                if candidate_key not in reserved:
                    final_name = candidate
                    final_key = candidate_key
                    reserved.add(final_key)
                    break
                number += 1
        seen.add(key)
        Preset.objects.filter(pk=row['pk']).update(
            name=final_name,
            search_name=final_key,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('plate_cutting', '0002_plate_cutting_package_count_limits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platecuttingpreset',
            name='set_quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)], verbose_name='Количество наборов'),
        ),
        migrations.AlterField(
            model_name='platecuttingpreset',
            name='search_name',
            field=models.CharField(max_length=120, verbose_name='Ключ поиска'),
        ),
        migrations.RunPython(
            normalize_and_deduplicate_names,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='platecuttingpreset',
            constraint=models.UniqueConstraint(fields=('search_name',), name='unique_plate_cutting_preset_search_name'),
        ),
        migrations.AddConstraint(
            model_name='platecuttingpreset',
            constraint=models.CheckConstraint(condition=models.Q(('set_quantity__gte', 1)), name='plate_cutting_preset_set_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='platecuttingpreset',
            constraint=models.CheckConstraint(condition=models.Q(('set_quantity__lte', 1000000)), name='plate_cutting_preset_set_quantity_within_limit'),
        ),
    ]
