from django.urls import path

from . import views

app_name = 'documents'

urlpatterns = [
    # The browser itself. `browse` is the «Документация» root — a label, not a
    # folder row — and `folder` is any directory inside «Корпоративные
    # документы».
    path('', views.browse, name='browse'),
    path('folders/<int:folder_id>/', views.browse, name='folder'),

    # One search over both branches. GET only, and it never leaves the module.
    path('search/', views.search, name='search'),

    # Management: POST only, and each one checks the permission before the
    # method, so a forbidden URL answers 403 rather than 405.
    path('folders/create/', views.folder_create, name='folder_create'),
    path('folders/<int:folder_id>/create/', views.folder_create, name='subfolder_create'),
    path('folders/<int:folder_id>/rename/', views.folder_rename, name='folder_rename'),
    path('folders/<int:folder_id>/delete/', views.folder_delete, name='folder_delete'),
    path('folders/<int:folder_id>/upload/', views.document_upload, name='document_upload'),

    # One corporate document: its current version, its versions and its
    # history. Files are served only through these views, never from a media
    # URL. `document_download` is the unchanged pre-versioning URL and now
    # resolves to the current version.
    path('files/<int:document_id>/', views.document_detail, name='document_detail'),
    path('files/<int:document_id>/download/', views.document_download, name='document_download'),
    path('files/<int:document_id>/delete/', views.document_delete, name='document_delete'),
    path(
        'files/<int:document_id>/versions/add/',
        views.document_version_add,
        name='document_version_add',
    ),
    path(
        'files/<int:document_id>/versions/<int:version_id>/download/',
        views.document_version_download,
        name='document_version_download',
    ),
    path(
        'files/<int:document_id>/versions/<int:version_id>/restore/',
        views.document_version_restore,
        name='document_version_restore',
    ),

    # ------------------------------------------------------------------
    # «Вложения»: act, protocol and task files, read-only.
    #
    # The folders below are generated by `documents/references.py` and are not
    # rows, so none of the management URLs above can address them. The three
    # mutation-shaped routes at the end exist for exactly one reason: a direct
    # attempt to change a system attachment must answer «permission denied»
    # with a real 403, for every role, rather than a 404 that leaves the rule
    # unstated.
    # ------------------------------------------------------------------
    path('system/', views.system_root, name='system_root'),
    path('system/<slug:source>/', views.system_source, name='system_source'),
    path('system/<slug:source>/<int:object_id>/', views.system_record, name='system_record'),
    path(
        'system/<slug:source>/files/<int:attachment_id>/download/',
        views.system_download,
        name='system_download',
    ),
    path(
        'system/<slug:source>/<int:object_id>/upload/',
        views.system_readonly,
        name='system_upload',
    ),
    path(
        'system/<slug:source>/files/<int:attachment_id>/delete/',
        views.system_readonly,
        name='system_delete',
    ),
    path(
        'system/<slug:source>/files/<int:attachment_id>/rename/',
        views.system_readonly,
        name='system_rename',
    ),
]
