"""The documentation file browser.

Two branches, and they behave differently on purpose.

«Корпоративные документы» is the library the project owns: real
`DocumentFolder` and `Document` rows, created and removed by administrators
through `documents/services.py`.

«Вложения» is a view of files that already belong to somebody else — act,
protocol and task attachments — generated by `documents/references.py`. It
stores nothing, copies nothing, and accepts no write from any role.

Two things every endpoint below does deliberately:

* the permission is checked *before* the HTTP method, so a user who types a
  management URL into the address bar gets a genuine 403 and not a «method not
  allowed» that hides the real answer;
* a file is never reachable by its media path. Both download views look the
  row up, re-ask the rule that owns it — `documents` for a corporate document,
  `acts`/`protocols`/`tasks` for a system attachment — and only then open
  storage.
"""

import logging

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http import FileResponse, Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from ecosystem.logging_utils import log_event

from .forms import DocumentUploadForm, DocumentVersionForm, FolderForm
from .models import ROOT_FOLDER_LABEL, Document, DocumentFolder, DocumentVersion
from .permissions import (
    can_add_document_version,
    can_delete_document,
    can_delete_folder,
    can_download_document,
    can_download_document_version,
    can_manage_documents,
    can_modify_system_attachments,
    can_rename_folder,
    can_restore_document_version,
    can_view_document_history,
    can_view_documents,
    can_view_system_attachments,
)
from .references import SOURCES, SYSTEM_AREA_LABEL, get_source
from .search import build_search_state
from .selectors import build_breadcrumbs, build_document_breadcrumbs, build_recent_documents
from .services import (
    DocumentError,
    add_document_version,
    create_folder,
    delete_document,
    delete_folder,
    rename_folder,
    restore_document_version,
    upload_document,
)


logger = logging.getLogger('ecosystem.documents')


def _browse_url(folder):
    """The browse URL for a folder, or for the root when it is None."""
    if folder is None:
        return reverse('documents:browse')
    return reverse('documents:folder', args=[folder.pk])


def _require_manage(user):
    """The one gate every management endpoint passes through."""
    if not can_manage_documents(user):
        log_event(
            logger,
            'WARNING',
            'documents.access_denied',
            user_id=getattr(user, 'pk', None),
            outcome='denied',
        )
        raise PermissionDenied('Недостаточно прав для изменения документации.')


@login_required
def browse(request, folder_id=None):
    """The folder listing: breadcrumbs, subfolders, documents, and the tools."""
    if not can_view_documents(request.user):
        raise PermissionDenied('Недостаточно прав для просмотра документации.')

    folder = None
    if folder_id is not None:
        folder = get_object_or_404(DocumentFolder.objects.select_related('parent'), pk=folder_id)

    subfolders = list(
        DocumentFolder.objects.filter(parent=folder).order_by('name', 'pk')
    )
    # The root is a label, not a row, so nothing can be stored directly in it:
    # every document belongs to a real folder.
    documents = (
        list(
            Document.objects.filter(folder=folder)
            .select_related('uploaded_by')
            .prefetch_related(Document.current_version_prefetch())
            .order_by('name', 'pk')
        )
        if folder is not None
        else []
    )

    can_manage = can_manage_documents(request.user)
    context = {
        'active_page': 'documents',
        'page_title': folder.name if folder else ROOT_FOLDER_LABEL,
        'header_title': ROOT_FOLDER_LABEL,
        'folder': folder,
        'parent_url': _browse_url(folder.parent) if folder is not None else None,
        'breadcrumbs': build_breadcrumbs(folder),
        'subfolders': subfolders,
        'documents': documents,
        'can_manage': can_manage,
        'can_rename_current': folder is not None and can_rename_folder(folder, request.user),
        'can_delete_current': folder is not None and can_delete_folder(folder, request.user),
        # The root holds the two system branches and nothing else, so neither
        # a new folder nor a file is created directly in it.
        'can_create_here': can_manage and folder is not None,
        'can_upload_here': can_manage and folder is not None,
        # Shown at the root only: the generated «Вложения» branch, which has no
        # folder row and therefore can never appear in `subfolders`.
        'system_entry': (
            {
                'name': SYSTEM_AREA_LABEL,
                'url': reverse('documents:system_root'),
                'description': 'Файлы актов, протоколов и задач — только для чтения',
            }
            if folder is None and can_view_system_attachments(request.user)
            else None
        ),
        # A shortcut into the newest files, root page only: deeper levels
        # already show the folder's own listing.
        'recent_documents': build_recent_documents(request.user) if folder is None else [],
        'folder_form': FolderForm(),
        'upload_form': DocumentUploadForm(),
    }
    return render(request, 'documents/browse.html', context)


@login_required
def search(request):
    """One result list over corporate documents and system attachments.

    The view parses nothing and matches nothing: `build_search_state()` reads
    the two GET parameters, runs `documents/search/` once and returns the
    chips, their counts and the narrowed list. Visibility comes from the same
    rules the browser uses, so a hit is always something this user could have
    reached by clicking.
    """
    if not can_view_documents(request.user):
        raise PermissionDenied('Недостаточно прав для просмотра документации.')

    context = {
        'active_page': 'documents',
        'page_title': 'Поиск по документации',
        'header_title': ROOT_FOLDER_LABEL,
    }
    context.update(build_search_state(request.user, request.GET))
    return render(request, 'documents/search.html', context)


@login_required
def folder_create(request, folder_id=None):
    """Create a subfolder of `folder_id`.

    Without one the target is the root, which the service refuses: the root
    holds «Корпоративные документы» and «Вложения» and nothing else.
    """
    _require_manage(request.user)
    parent = (
        get_object_or_404(DocumentFolder, pk=folder_id) if folder_id is not None else None
    )
    if request.method != 'POST':
        return redirect(_browse_url(parent))

    form = FolderForm(request.POST)
    if not form.is_valid():
        messages.error(request, form.errors['name'][0])
        return redirect(_browse_url(parent))
    try:
        folder = create_folder(parent, form.cleaned_data['name'], request.user)
    except DocumentError as exc:
        messages.error(request, str(exc))
        return redirect(_browse_url(parent))
    messages.success(request, f'Папка «{folder.name}» создана.')
    return redirect(_browse_url(parent))


@login_required
def folder_rename(request, folder_id):
    folder = get_object_or_404(DocumentFolder.objects.select_related('parent'), pk=folder_id)
    _require_manage(request.user)
    if request.method != 'POST':
        return redirect(_browse_url(folder))

    form = FolderForm(request.POST)
    if not form.is_valid():
        messages.error(request, form.errors['name'][0])
        return redirect(_browse_url(folder))
    try:
        rename_folder(folder, form.cleaned_data['name'], request.user)
    except DocumentError as exc:
        messages.error(request, str(exc))
    else:
        messages.success(request, 'Папка переименована.')
    return redirect(_browse_url(folder))


@login_required
def folder_delete(request, folder_id):
    """Delete a folder with its subfolders and files, then open its parent."""
    folder = get_object_or_404(DocumentFolder.objects.select_related('parent'), pk=folder_id)
    _require_manage(request.user)
    if request.method != 'POST':
        return redirect(_browse_url(folder))

    try:
        parent = delete_folder(folder, request.user)
    except DocumentError as exc:
        messages.error(request, str(exc))
        return redirect(_browse_url(folder))
    messages.success(request, 'Папка удалена.')
    return redirect(_browse_url(parent))


@login_required
def document_upload(request, folder_id):
    folder = get_object_or_404(DocumentFolder, pk=folder_id)
    _require_manage(request.user)
    if request.method != 'POST':
        return redirect(_browse_url(folder))

    form = DocumentUploadForm(request.POST, request.FILES)
    if not form.is_valid():
        first_error = next(iter(form.errors.values()))[0]
        messages.error(request, first_error)
        return redirect(_browse_url(folder))
    try:
        document = upload_document(
            folder,
            form.cleaned_data['file'],
            request.user,
            name=form.cleaned_data.get('name', ''),
        )
    except DocumentError as exc:
        messages.error(request, str(exc))
        return redirect(_browse_url(folder))
    messages.success(request, f'Документ «{document.name}» загружен.')
    return redirect(_browse_url(folder))


@login_required
def document_download(request, document_id):
    """Stream one corporate document after re-checking who may read the library.

    A refusal and a missing file are the same 404 to the client; the
    difference goes to the log, as identifiers only.
    """
    document = get_object_or_404(
        Document.objects.select_related('folder', 'uploaded_by'), pk=document_id
    )
    if not can_download_document(document, request.user):
        log_event(
            logger,
            'WARNING',
            'documents.access_denied',
            document_id=document.pk,
            user_id=getattr(request.user, 'pk', None),
            operation='download',
            outcome='denied',
        )
        raise Http404('No Document matches the given query.')
    version = document.current_version
    if version is None:
        raise Http404('Document has no current version.')
    return _stream_version(request, version, 'download')


def _stream_version(request, version, operation):
    """Open one version's stored file and hand it to the browser.

    Shared by the document download — which resolves the current version — and
    by the per-version download, so both answer identically for a row whose
    file has gone missing.
    """
    if not version.file:
        raise Http404('Document file is missing.')
    try:
        handle = version.file.open('rb')
    except OSError as exc:
        log_event(
            logger,
            'ERROR',
            'documents.storage_failed',
            document_id=version.document_id,
            version_number=version.number,
            user_id=getattr(request.user, 'pk', None),
            operation=operation,
            error_type=type(exc).__name__,
            outcome='failed',
            exc_info=True,
        )
        raise Http404('Document file is missing.') from exc

    log_event(
        logger,
        'INFO',
        'documents.downloaded',
        document_id=version.document_id,
        version_number=version.number,
        user_id=getattr(request.user, 'pk', None),
        size_bytes=version.file_size,
        operation=operation,
        outcome='ok',
    )
    return FileResponse(
        handle,
        as_attachment=True,
        filename=version.original_name or version.document.name,
        content_type=version.content_type or 'application/octet-stream',
    )


@login_required
def document_detail(request, document_id):
    """One document: its current version, its history, and the upload form.

    The page every corporate file now has. Reading it is reading the library;
    the «новая версия» form and the restore buttons are drawn only for a
    document manager, and each posts to an endpoint that asks the same rule
    again.
    """
    document = get_object_or_404(
        Document.objects.select_related('folder', 'folder__parent', 'uploaded_by'),
        pk=document_id,
    )
    if not can_view_documents(request.user):
        raise PermissionDenied('Недостаточно прав для просмотра документации.')

    versions = list(document.versions.select_related('uploaded_by').order_by('-number', '-pk'))
    current = next((version for version in versions if version.is_current), None)
    can_manage = can_add_document_version(document, request.user)
    context = {
        'active_page': 'documents',
        'page_title': document.name,
        'header_title': ROOT_FOLDER_LABEL,
        'document': document,
        'folder': document.folder,
        'parent_url': _browse_url(document.folder),
        'breadcrumbs': build_document_breadcrumbs(document),
        'current_version': current,
        'versions': versions,
        'history': (
            list(document.history.select_related('user').order_by('-created_at', '-pk')[:50])
            if can_view_document_history(document, request.user)
            else []
        ),
        'can_manage': can_manage,
        'can_restore': can_restore_document_version(document, request.user),
        'can_delete': can_delete_document(document, request.user),
        'version_form': DocumentVersionForm(),
    }
    return render(request, 'documents/document.html', context)


@login_required
def document_version_add(request, document_id):
    """Upload a new current version. Never overwrites the previous one."""
    document = get_object_or_404(Document.objects.select_related('folder'), pk=document_id)
    _require_manage(request.user)
    detail_url = reverse('documents:document_detail', args=[document.pk])
    if request.method != 'POST':
        return redirect(detail_url)

    form = DocumentVersionForm(request.POST, request.FILES)
    if not form.is_valid():
        first_error = next(iter(form.errors.values()))[0]
        messages.error(request, first_error)
        return redirect(detail_url)
    try:
        version = add_document_version(
            document,
            form.cleaned_data['file'],
            request.user,
            comment=form.cleaned_data.get('comment', ''),
        )
    except DocumentError as exc:
        messages.error(request, str(exc))
        return redirect(detail_url)
    messages.success(request, f'Загружена версия {version.label}.')
    return redirect(detail_url)


@login_required
def document_version_download(request, document_id, version_id):
    """Download any version of a document — the current one or an earlier one.

    Scoped to the document in the path, so a version id cannot be used to
    reach a file under a document the URL does not name.
    """
    version = get_object_or_404(
        DocumentVersion.objects.select_related('document', 'document__folder'),
        pk=version_id,
        document_id=document_id,
    )
    if not can_download_document_version(version, request.user):
        log_event(
            logger,
            'WARNING',
            'documents.access_denied',
            document_id=version.document_id,
            version_number=version.number,
            user_id=getattr(request.user, 'pk', None),
            operation='version_download',
            outcome='denied',
        )
        raise Http404('No Document matches the given query.')
    return _stream_version(request, version, 'version_download')


@login_required
def document_version_restore(request, document_id, version_id):
    """Make an earlier version current again. Nothing is edited or removed."""
    version = get_object_or_404(
        DocumentVersion.objects.select_related('document'), pk=version_id, document_id=document_id
    )
    _require_manage(request.user)
    detail_url = reverse('documents:document_detail', args=[document_id])
    if request.method != 'POST':
        return redirect(detail_url)

    try:
        restore_document_version(version.document, version, request.user)
    except DocumentError as exc:
        messages.error(request, str(exc))
    else:
        messages.success(request, f'Версия {version.label} снова стала текущей.')
    return redirect(detail_url)


@login_required
def document_delete(request, document_id):
    document = get_object_or_404(Document.objects.select_related('folder'), pk=document_id)
    _require_manage(request.user)
    folder = document.folder
    if request.method != 'POST':
        return redirect(_browse_url(folder))

    if not can_delete_document(document, request.user):
        raise PermissionDenied('Недостаточно прав для удаления документа.')
    try:
        delete_document(document, request.user)
    except DocumentError as exc:
        messages.error(request, str(exc))
    else:
        messages.success(request, 'Документ удалён.')
    return redirect(_browse_url(folder))


# ---------------------------------------------------------------------------
# «Вложения» — act, protocol and task files, read-only
#
# Three listing levels and one download. None of them touches a
# `DocumentFolder` or a `Document`: the tree is generated by
# `documents/references.py` from the tables that already own the files, so
# there is nothing here for the management endpoints above to address even in
# principle. `system_readonly` states the refusal out loud anyway.
# ---------------------------------------------------------------------------


def _require_system_view(user):
    if not can_view_system_attachments(user):
        raise PermissionDenied('Недостаточно прав для просмотра вложений.')


def _system_breadcrumbs(source=None, record_label='', record_id=None):
    """The same clickable trail as the corporate side, one label deeper."""
    trail = [
        {'name': ROOT_FOLDER_LABEL, 'url': reverse('documents:browse'), 'is_current': False},
        {
            'name': SYSTEM_AREA_LABEL,
            'url': reverse('documents:system_root'),
            'is_current': source is None,
        },
    ]
    if source is None:
        return trail
    trail.append({
        'name': source.label,
        'url': reverse('documents:system_source', args=[source.slug]),
        'is_current': record_id is None,
    })
    if record_id is not None:
        trail.append({
            'name': record_label,
            'url': reverse('documents:system_record', args=[source.slug, record_id]),
            'is_current': True,
        })
    return trail


def _system_context(**extra):
    """The context every «Вложения» page shares."""
    context = {
        'active_page': 'documents',
        'header_title': ROOT_FOLDER_LABEL,
        'is_system_area': True,
        'source_folders': [],
        'groups': [],
        'references': [],
        'record_url': '',
        'record_label': '',
    }
    context.update(extra)
    return context


@login_required
def system_root(request):
    """«Вложения»: one generated folder per integrated module."""
    _require_system_view(request.user)
    context = _system_context(
        page_title=SYSTEM_AREA_LABEL,
        breadcrumbs=_system_breadcrumbs(),
        parent_url=reverse('documents:browse'),
        source_folders=[
            {'name': source.label, 'url': reverse('documents:system_source', args=[source.slug])}
            for source in SOURCES.values()
        ],
    )
    return render(request, 'documents/system.html', context)


@login_required
def system_source(request, source):
    """One module's records that have attachments, as generated folders."""
    _require_system_view(request.user)
    adapter = get_source(source)
    if adapter is None:
        raise Http404('Unknown attachment source.')
    context = _system_context(
        page_title=adapter.label,
        breadcrumbs=_system_breadcrumbs(adapter),
        parent_url=reverse('documents:system_root'),
        groups=adapter.groups(request.user),
    )
    return render(request, 'documents/system.html', context)


@login_required
def system_record(request, source, object_id):
    """The files of one act, protocol or task."""
    _require_system_view(request.user)
    adapter = get_source(source)
    if adapter is None:
        raise Http404('Unknown attachment source.')
    # A record this user may not read is absent, not forbidden — the same
    # answer the owning module gives.
    record = adapter.get_record(request.user, object_id)
    if record is None:
        raise Http404('No source record matches the given query.')

    label = adapter.record_label(record)
    context = _system_context(
        page_title=label,
        breadcrumbs=_system_breadcrumbs(adapter, label, record.pk),
        parent_url=reverse('documents:system_source', args=[adapter.slug]),
        record_url=adapter.record_url(record),
        record_label=label,
        references=adapter.references(request.user, record),
    )
    return render(request, 'documents/system.html', context)


@login_required
def system_download(request, source, attachment_id):
    """Stream an existing system attachment from where it already lives.

    No copy is made and no path is built here: the row's own `FileField` is
    opened, and `resolve_attachment()` has already re-asked the owning app
    whether this user may read it.
    """
    _require_system_view(request.user)
    adapter = get_source(source)
    if adapter is None:
        raise Http404('Unknown attachment source.')
    attachment = adapter.resolve_attachment(request.user, attachment_id)
    if attachment is None:
        log_event(
            logger,
            'WARNING',
            'documents.access_denied',
            source=source,
            attachment_id=attachment_id,
            user_id=getattr(request.user, 'pk', None),
            operation='system_download',
            outcome='denied',
        )
        raise Http404('No attachment matches the given query.')
    if not attachment.file:
        raise Http404('Attachment file is missing.')
    try:
        handle = attachment.file.open('rb')
    except OSError as exc:
        log_event(
            logger,
            'ERROR',
            'documents.storage_failed',
            source=source,
            attachment_id=attachment.pk,
            user_id=getattr(request.user, 'pk', None),
            operation='system_download',
            error_type=type(exc).__name__,
            outcome='failed',
            exc_info=True,
        )
        raise Http404('Attachment file is missing.') from exc

    log_event(
        logger,
        'INFO',
        'documents.system_downloaded',
        source=source,
        attachment_id=attachment.pk,
        user_id=getattr(request.user, 'pk', None),
        size_bytes=attachment.file_size,
        operation='system_download',
        outcome='ok',
    )
    return FileResponse(
        handle,
        as_attachment=True,
        filename=attachment.original_name,
        content_type=attachment.content_type or 'application/octet-stream',
    )


@login_required
def system_readonly(request, *args, **kwargs):
    """Every write against the «Вложения» branch, refused for every role.

    Registered on upload-, delete- and rename-shaped URLs so a direct attempt
    gets a 403 that means what it says, on GET as well as POST.
    `can_modify_system_attachments()` is the single answer, and it is False for
    administrators and superusers too: these files belong to the act, protocol
    or task that owns them, and to the quality history that records them.
    """
    if not can_modify_system_attachments(request.user):
        log_event(
            logger,
            'WARNING',
            'documents.system_modification_denied',
            source=kwargs.get('source', ''),
            user_id=getattr(request.user, 'pk', None),
            method=request.method,
            outcome='denied',
        )
        raise PermissionDenied(
            'Системные вложения доступны только для чтения. Файл изменяется там, '
            'где он был загружен.'
        )
    # Unreachable while the rule above holds. Left as an explicit branch
    # rather than as an assumption about it.
    raise Http404('No document matches the given query.')
