"""The documentation file browser.

Two branches, and they behave differently on purpose.

«Корпоративные документы» is the library the project owns: real
`DocumentFolder` and `Document` rows, created and removed by administrators
through `documents/services.py`.

«Вложения» is a view of files that already belong to somebody else — act,
protocol and task attachments — generated by `documents/references.py`. It
stores nothing, copies nothing, and accepts no write from any role.

Two things every endpoint below does deliberately:

* the permission is checked *before* the HTTP method, so a user who types a
  management URL into the address bar gets a genuine 403 and not a «method not
  allowed» that hides the real answer;
* a file is never reachable by its media path. Both download views look the
  row up, re-ask the rule that owns it — `documents` for a corporate document,
  `acts`/`protocols`/`tasks` for a system attachment — and only then open
  storage.
"""

import logging

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http import FileResponse, Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from ecosystem.logging_utils import log_event

from .cards import file_icon
from .forms import DocumentUploadForm, DocumentVersionForm, FolderForm
from .models import ROOT_FOLDER_LABEL, Document, DocumentFolder, DocumentVersion
from .permissions import (
    can_add_document_version,
    can_delete_document,
    can_download_document,
    can_download_document_version,
    can_favorite_document,
    can_manage_documents,
    can_modify_system_attachments,
    can_restore_document_version,
    can_view_document_history,
    can_view_documents,
    can_view_system_attachments,
)
from .preview import describe_preview, inline_content_type
from .references import SOURCES, SYSTEM_AREA_LABEL, get_source
from .search import build_search_state
from .selectors import (
    build_breadcrumbs,
    build_document_breadcrumbs,
    build_document_cards,
    build_folder_rows,
    build_favorite_documents,
    build_recent_documents,
    build_version_rows,
)
from .services import (
    DocumentError,
    add_document_version,
    create_folder,
    delete_document,
    delete_folder,
    rename_folder,
    restore_document_version,
    toggle_document_favorite,
    upload_documents,
)


logger = logging.getLogger('ecosystem.documents')


def _browse_url(folder):
    """The browse URL for a folder, or for the root when it is None."""
    if folder is None:
        return reverse('documents:browse')
    return reverse('documents:folder', args=[folder.pk])


def _require_manage(user):
    """The one gate every management endpoint passes through."""
    if not can_manage_documents(user):
        log_event(
            logger,
            'WARNING',
            'documents.access_denied',
            user_id=getattr(user, 'pk', None),
            outcome='denied',
        )
        raise PermissionDenied('Недостаточно прав для изменения документации.')


@login_required
def browse(request, folder_id=None):
    """The folder listing: breadcrumbs, subfolders, documents, and the tools."""
    if not can_view_documents(request.user):
        raise PermissionDenied('Недостаточно прав для просмотра документации.')

    folder = None
    if folder_id is not None:
        folder = get_object_or_404(DocumentFolder.objects.select_related('parent'), pk=folder_id)

    subfolders = build_folder_rows(
        DocumentFolder.objects.filter(parent=folder).order_by('name', 'pk'), request.user
    )
    # The root is a label, not a row, so nothing can be stored directly in it:
    # every document belongs to a real folder.
    document_cards = []
    if folder is not None:
        document_cards = build_document_cards(
            Document.objects.filter(folder=folder)
            .select_related('uploaded_by')
            .prefetch_related(Document.current_version_prefetch())
            .order_by('name', 'pk'),
            request.user,
            # Every document in a folder shares its location, so the path is
            # built once rather than per card.
            path=' / '.join([ROOT_FOLDER_LABEL, *(entry.name for entry in folder.breadcrumbs())]),
        )

    can_manage = can_manage_documents(request.user)
    context = {
        'active_page': 'documents',
        'page_title': folder.name if folder else ROOT_FOLDER_LABEL,
        'header_title': ROOT_FOLDER_LABEL,
        'folder': folder,
        'parent_url': _browse_url(folder.parent) if folder is not None else None,
        'breadcrumbs': build_breadcrumbs(folder),
        'subfolders': subfolders,
        'documents': document_cards,
        'can_manage': can_manage,
        # A folder is renamed and deleted from the «Действия» column of the
        # listing it appears in, never from its own page: one place for the
        # action, and the row it belongs to is right next to it.
        # The root holds the two system branches and nothing else, so neither
        # a new folder nor a file is created directly in it.
        'can_create_here': can_manage and folder is not None,
        'can_upload_here': can_manage and folder is not None,
        # Shown at the root only: the generated «Вложения» branch, which has no
        # folder row and therefore can never appear in `subfolders`.
        'system_entry': (
            {
                'name': SYSTEM_AREA_LABEL,
                'url': reverse('documents:system_root'),
                'description': 'Файлы актов, протоколов и задач — только для чтения',
            }
            if folder is None and can_view_system_attachments(request.user)
            else None
        ),
        # Personal shortcuts, root page only: deeper levels already show the
        # folder's own listing. Favourites are this user's and nobody else's.
        'favorite_documents': build_favorite_documents(request.user) if folder is None else [],
        'recent_documents': build_recent_documents(request.user) if folder is None else [],
        'folder_form': FolderForm(),
        'upload_form': DocumentUploadForm(),
    }
    return render(request, 'documents/browse.html', context)


@login_required
def search(request):
    """One result list over corporate documents and system attachments.

    The view parses nothing and matches nothing: `build_search_state()` reads
    the two GET parameters, runs `documents/search/` once and returns the
    chips, their counts and the narrowed list. Visibility comes from the same
    rules the browser uses, so a hit is always something this user could have
    reached by clicking.
    """
    if not can_view_documents(request.user):
        raise PermissionDenied('Недостаточно прав для просмотра документации.')

    context = {
        'active_page': 'documents',
        'page_title': 'Поиск по документации',
        'header_title': ROOT_FOLDER_LABEL,
    }
    context.update(build_search_state(request.user, request.GET))
    return render(request, 'documents/search.html', context)


@login_required
def folder_create(request, folder_id=None):
    """Create a subfolder of `folder_id`.

    Without one the target is the root, which the service refuses: the root
    holds «Корпоративные документы» and «Вложения» and nothing else.
    """
    _require_manage(request.user)
    parent = (
        get_object_or_404(DocumentFolder, pk=folder_id) if folder_id is not None else None
    )
    if request.method != 'POST':
        return redirect(_browse_url(parent))

    form = FolderForm(request.POST)
    if not form.is_valid():
        messages.error(request, form.errors['name'][0])
        return redirect(_browse_url(parent))
    try:
        folder = create_folder(parent, form.cleaned_data['name'], request.user)
    except DocumentError as exc:
        messages.error(request, str(exc))
        return redirect(_browse_url(parent))
    messages.success(request, f'Папка «{folder.name}» создана.')
    return redirect(_browse_url(parent))


@login_required
def folder_rename(request, folder_id):
    folder = get_object_or_404(DocumentFolder.objects.select_related('parent'), pk=folder_id)
    _require_manage(request.user)
    if request.method != 'POST':
        return redirect(_browse_url(folder))

    form = FolderForm(request.POST)
    if not form.is_valid():
        messages.error(request, form.errors['name'][0])
        return redirect(_browse_url(folder))
    try:
        rename_folder(folder, form.cleaned_data['name'], request.user)
    except DocumentError as exc:
        messages.error(request, str(exc))
    else:
        messages.success(request, 'Папка переименована.')
    return redirect(_browse_url(folder))


@login_required
def folder_delete(request, folder_id):
    """Delete a folder with its subfolders and files, then open its parent."""
    folder = get_object_or_404(DocumentFolder.objects.select_related('parent'), pk=folder_id)
    _require_manage(request.user)
    if request.method != 'POST':
        return redirect(_browse_url(folder))

    try:
        parent = delete_folder(folder, request.user)
    except DocumentError as exc:
        messages.error(request, str(exc))
        return redirect(_browse_url(folder))
    messages.success(request, 'Папка удалена.')
    return redirect(_browse_url(parent))


@login_required
def document_upload(request, folder_id):
    folder = get_object_or_404(DocumentFolder, pk=folder_id)
    _require_manage(request.user)
    if request.method != 'POST':
        return redirect(_browse_url(folder))

    form = DocumentUploadForm(request.POST, request.FILES)
    if not form.is_valid():
        first_error = next(iter(form.errors.values()))[0]
        messages.error(request, first_error)
        return redirect(_browse_url(folder))
    try:
        created, errors = upload_documents(
            folder, form.cleaned_data['file'], request.user
        )
    except DocumentError as exc:
        messages.error(request, str(exc))
        return redirect(_browse_url(folder))

    if len(created) == 1:
        messages.success(request, f'Документ «{created[0].name}» загружен.')
    elif created:
        messages.success(request, f'Загружено документов: {len(created)}.')
    # A partly refused selection reports both halves: what was stored, and
    # what was not and why.
    for error in errors:
        messages.error(request, error)
    return redirect(_browse_url(folder))


@login_required
def document_download(request, document_id):
    """Stream one corporate document after re-checking who may read the library.

    A refusal and a missing file are the same 404 to the client; the
    difference goes to the log, as identifiers only.
    """
    document = get_object_or_404(
        Document.objects.select_related('folder', 'uploaded_by'), pk=document_id
    )
    if not can_download_document(document, request.user):
        log_event(
            logger,
            'WARNING',
            'documents.access_denied',
            document_id=document.pk,
            user_id=getattr(request.user, 'pk', None),
            operation='download',
            outcome='denied',
        )
        raise Http404('No Document matches the given query.')
    version = document.current_version
    if version is None:
        raise Http404('Document has no current version.')
    return _stream_version(request, version, 'download')


def _stream_version(request, version, operation):
    """Open one version's stored file and hand it to the browser.

    Shared by the document download — which resolves the current version — and
    by the per-version download, so both answer identically for a row whose
    file has gone missing.
    """
    if not version.file:
        raise Http404('Document file is missing.')
    try:
        handle = version.file.open('rb')
    except OSError as exc:
        log_event(
            logger,
            'ERROR',
            'documents.storage_failed',
            document_id=version.document_id,
            version_number=version.number,
            user_id=getattr(request.user, 'pk', None),
            operation=operation,
            error_type=type(exc).__name__,
            outcome='failed',
            exc_info=True,
        )
        raise Http404('Document file is missing.') from exc

    log_event(
        logger,
        'INFO',
        'documents.downloaded',
        document_id=version.document_id,
        version_number=version.number,
        user_id=getattr(request.user, 'pk', None),
        size_bytes=version.file_size,
        operation=operation,
        outcome='ok',
    )
    return FileResponse(
        handle,
        as_attachment=True,
        filename=version.original_name or version.document.name,
        content_type=version.content_type or 'application/octet-stream',
    )


DOCUMENT_TABS = ('document', 'history')


@login_required
def document_detail(request, document_id):
    """One document: its header, the file itself, and — on its own tab — history.

    Two tabs, the same `?tab=` pattern acts and protocols use: «Документ» is
    the information block plus the viewer, «История» is every version and every
    recorded event. The version table is deliberately absent from the first
    tab — a reader wants the file, not the audit trail.

    `?version=` chooses which revision is on screen. It is a plain query
    parameter and not session state, so the address bar always says which
    revision is being read and a link to it can be pasted to somebody else.
    """
    document = get_object_or_404(
        Document.objects.select_related('folder', 'folder__parent', 'uploaded_by'),
        pk=document_id,
    )
    if not can_view_documents(request.user):
        raise PermissionDenied('Недостаточно прав для просмотра документации.')

    requested_tab = request.GET.get('tab')
    detail_tab = requested_tab if requested_tab in DOCUMENT_TABS else 'document'

    versions = list(document.versions.select_related('uploaded_by').order_by('-number', '-pk'))
    current = next((version for version in versions if version.is_current), None)
    # An unknown or foreign `?version=` falls back to the current one rather
    # than 404ing: the parameter selects a view, it does not address a file.
    selected = current
    requested_version = request.GET.get('version')
    if requested_version and requested_version.isdigit():
        selected = next(
            (version for version in versions if version.pk == int(requested_version)), current
        )

    context = {
        'active_page': 'documents',
        'page_title': document.name,
        'header_title': ROOT_FOLDER_LABEL,
        'detail_tab': detail_tab,
        'document': document,
        'folder': document.folder,
        'parent_url': _browse_url(document.folder),
        'breadcrumbs': build_document_breadcrumbs(document),
        'icon': file_icon(current.original_name if current else document.name),
        'current_version': current,
        'selected_version': selected,
        'version_rows': build_version_rows(document, versions, selected),
        'is_viewing_current': selected is not None and selected.is_current,
        'preview': describe_preview(selected),
        'preview_url': (
            reverse('documents:document_version_preview', args=[document.pk, selected.pk])
            if selected is not None
            else ''
        ),
        'can_manage': can_add_document_version(document, request.user),
        'can_favorite': can_favorite_document(document, request.user),
        'is_favorite': (
            document.favorites.filter(user=request.user).exists()
            if request.user.is_authenticated
            else False
        ),
        'can_restore': can_restore_document_version(document, request.user),
        'can_delete': can_delete_document(document, request.user),
        'version_form': DocumentVersionForm(),
    }
    if detail_tab == 'history':
        context['history'] = (
            list(document.history.select_related('user').order_by('-created_at', '-pk')[:50])
            if can_view_document_history(document, request.user)
            else []
        )
    return render(request, 'documents/document.html', context)


@login_required
def document_version_preview(request, document_id, version_id):
    """Serve one version inline, for the viewer on the document page.

    The same read rule as the download — this is the same file, shown rather
    than saved — and three deliberate differences from `_stream_version()`:

    * the content type comes from `documents/preview.py`'s own map, keyed on
      the file's extension, never from the `content_type` recorded at upload:
      that value came from the browser and may claim anything;
    * an extension with no entry is a 404, so nothing outside the safe set is
      ever sent inline;
    * `nosniff` and a sandbox CSP travel with the response, so a crafted file
      cannot be re-interpreted as script running on this origin.
    """
    version = get_object_or_404(
        DocumentVersion.objects.select_related('document'),
        pk=version_id,
        document_id=document_id,
    )
    if not can_download_document_version(version, request.user):
        raise Http404('No Document matches the given query.')
    content_type = inline_content_type(version.extension)
    if content_type is None or not version.file:
        raise Http404('Preview is not available for this file.')
    try:
        handle = version.file.open('rb')
    except OSError as exc:
        raise Http404('Document file is missing.') from exc

    response = FileResponse(
        handle,
        as_attachment=False,
        filename=version.original_name,
        content_type=content_type,
    )
    response['X-Content-Type-Options'] = 'nosniff'
    # The strictest sandbox the file still renders under: no scripts, no forms,
    # no navigation, no same-origin privileges.
    response['Content-Security-Policy'] = 'sandbox'
    return response


@login_required
def favorite_toggle(request, document_id):
    """Star or unstar one document, for the user who asked.

    Personal state: the row is keyed on `request.user`, so nothing here can
    change what anybody else sees. Only corporate documents have this — a
    system attachment has no `Document` row to point at.
    """
    document = get_object_or_404(Document.objects.select_related('folder'), pk=document_id)
    if not can_favorite_document(document, request.user):
        raise PermissionDenied('Недостаточно прав для работы с избранным.')

    fallback = reverse('documents:document_detail', args=[document.pk])
    if request.method != 'POST':
        return redirect(fallback)
    try:
        is_favorite = toggle_document_favorite(document, request.user)
    except DocumentError as exc:
        messages.error(request, str(exc))
        return redirect(fallback)

    messages.success(
        request,
        'Документ добавлен в избранное.' if is_favorite else 'Документ убран из избранного.',
    )
    # Back to the page the star was clicked on, when it is one of ours: a
    # favourite is toggled from the folder listing and from the root just as
    # often as from the document page.
    return redirect(_safe_next(request, fallback))


def _safe_next(request, fallback):
    """The posted `next`, but only when it is a path inside this site.

    An absolute or scheme-relative value is discarded: a redirect target that
    came from a form is user input, and following it off-site would turn this
    endpoint into an open redirect.
    """
    target = (request.POST.get('next') or '').strip()
    if target.startswith('/') and not target.startswith('//'):
        return target
    return fallback


@login_required
def document_version_add(request, document_id):
    """Upload a new current version. Never overwrites the previous one."""
    document = get_object_or_404(Document.objects.select_related('folder'), pk=document_id)
    _require_manage(request.user)
    detail_url = reverse('documents:document_detail', args=[document.pk])
    if request.method != 'POST':
        return redirect(detail_url)

    form = DocumentVersionForm(request.POST, request.FILES)
    if not form.is_valid():
        first_error = next(iter(form.errors.values()))[0]
        messages.error(request, first_error)
        return redirect(detail_url)
    try:
        version = add_document_version(
            document,
            form.cleaned_data['file'],
            request.user,
            comment=form.cleaned_data.get('comment', ''),
        )
    except DocumentError as exc:
        messages.error(request, str(exc))
        return redirect(detail_url)
    messages.success(request, f'Загружена версия {version.label}.')
    return redirect(detail_url)


@login_required
def document_version_download(request, document_id, version_id):
    """Download any version of a document — the current one or an earlier one.

    Scoped to the document in the path, so a version id cannot be used to
    reach a file under a document the URL does not name.
    """
    version = get_object_or_404(
        DocumentVersion.objects.select_related('document', 'document__folder'),
        pk=version_id,
        document_id=document_id,
    )
    if not can_download_document_version(version, request.user):
        log_event(
            logger,
            'WARNING',
            'documents.access_denied',
            document_id=version.document_id,
            version_number=version.number,
            user_id=getattr(request.user, 'pk', None),
            operation='version_download',
            outcome='denied',
        )
        raise Http404('No Document matches the given query.')
    return _stream_version(request, version, 'version_download')


@login_required
def document_version_restore(request, document_id, version_id):
    """Make an earlier version current again. Nothing is edited or removed."""
    version = get_object_or_404(
        DocumentVersion.objects.select_related('document'), pk=version_id, document_id=document_id
    )
    _require_manage(request.user)
    detail_url = reverse('documents:document_detail', args=[document_id])
    if request.method != 'POST':
        return redirect(detail_url)

    try:
        restore_document_version(version.document, version, request.user)
    except DocumentError as exc:
        messages.error(request, str(exc))
    else:
        messages.success(request, f'Версия {version.label} снова стала текущей.')
    return redirect(detail_url)


@login_required
def document_delete(request, document_id):
    document = get_object_or_404(Document.objects.select_related('folder'), pk=document_id)
    _require_manage(request.user)
    folder = document.folder
    if request.method != 'POST':
        return redirect(_browse_url(folder))

    if not can_delete_document(document, request.user):
        raise PermissionDenied('Недостаточно прав для удаления документа.')
    try:
        delete_document(document, request.user)
    except DocumentError as exc:
        messages.error(request, str(exc))
    else:
        messages.success(request, 'Документ удалён.')
    return redirect(_browse_url(folder))


# ---------------------------------------------------------------------------
# «Вложения» — act, protocol and task files, read-only
#
# Three listing levels and one download. None of them touches a
# `DocumentFolder` or a `Document`: the tree is generated by
# `documents/references.py` from the tables that already own the files, so
# there is nothing here for the management endpoints above to address even in
# principle. `system_readonly` states the refusal out loud anyway.
# ---------------------------------------------------------------------------


def _require_system_view(user):
    if not can_view_system_attachments(user):
        raise PermissionDenied('Недостаточно прав для просмотра вложений.')


def _system_breadcrumbs(source=None, record_label='', record_id=None):
    """The same clickable trail as the corporate side, one label deeper."""
    trail = [
        {'name': ROOT_FOLDER_LABEL, 'url': reverse('documents:browse'), 'is_current': False},
        {
            'name': SYSTEM_AREA_LABEL,
            'url': reverse('documents:system_root'),
            'is_current': source is None,
        },
    ]
    if source is None:
        return trail
    trail.append({
        'name': source.label,
        'url': reverse('documents:system_source', args=[source.slug]),
        'is_current': record_id is None,
    })
    if record_id is not None:
        trail.append({
            'name': record_label,
            'url': reverse('documents:system_record', args=[source.slug, record_id]),
            'is_current': True,
        })
    return trail


def _system_context(**extra):
    """The context every «Вложения» page shares."""
    context = {
        'active_page': 'documents',
        'header_title': ROOT_FOLDER_LABEL,
        'is_system_area': True,
        'source_folders': [],
        'groups': [],
        'references': [],
        'record_url': '',
        'record_label': '',
    }
    context.update(extra)
    return context


@login_required
def system_root(request):
    """«Вложения»: one generated folder per integrated module."""
    _require_system_view(request.user)
    context = _system_context(
        page_title=SYSTEM_AREA_LABEL,
        breadcrumbs=_system_breadcrumbs(),
        parent_url=reverse('documents:browse'),
        source_folders=[
            {'name': source.label, 'url': reverse('documents:system_source', args=[source.slug])}
            for source in SOURCES.values()
        ],
    )
    return render(request, 'documents/system.html', context)


@login_required
def system_source(request, source):
    """One module's records that have attachments, as generated folders."""
    _require_system_view(request.user)
    adapter = get_source(source)
    if adapter is None:
        raise Http404('Unknown attachment source.')
    context = _system_context(
        page_title=adapter.label,
        breadcrumbs=_system_breadcrumbs(adapter),
        parent_url=reverse('documents:system_root'),
        groups=adapter.groups(request.user),
    )
    return render(request, 'documents/system.html', context)


@login_required
def system_record(request, source, object_id):
    """The files of one act, protocol or task."""
    _require_system_view(request.user)
    adapter = get_source(source)
    if adapter is None:
        raise Http404('Unknown attachment source.')
    # A record this user may not read is absent, not forbidden — the same
    # answer the owning module gives.
    record = adapter.get_record(request.user, object_id)
    if record is None:
        raise Http404('No source record matches the given query.')

    label = adapter.record_label(record)
    context = _system_context(
        page_title=label,
        breadcrumbs=_system_breadcrumbs(adapter, label, record.pk),
        parent_url=reverse('documents:system_source', args=[adapter.slug]),
        record_url=adapter.record_url(record),
        record_label=label,
        references=adapter.references(request.user, record),
    )
    return render(request, 'documents/system.html', context)


@login_required
def system_download(request, source, attachment_id):
    """Stream an existing system attachment from where it already lives.

    No copy is made and no path is built here: the row's own `FileField` is
    opened, and `resolve_attachment()` has already re-asked the owning app
    whether this user may read it.
    """
    _require_system_view(request.user)
    adapter = get_source(source)
    if adapter is None:
        raise Http404('Unknown attachment source.')
    attachment = adapter.resolve_attachment(request.user, attachment_id)
    if attachment is None:
        log_event(
            logger,
            'WARNING',
            'documents.access_denied',
            source=source,
            attachment_id=attachment_id,
            user_id=getattr(request.user, 'pk', None),
            operation='system_download',
            outcome='denied',
        )
        raise Http404('No attachment matches the given query.')
    if not attachment.file:
        raise Http404('Attachment file is missing.')
    try:
        handle = attachment.file.open('rb')
    except OSError as exc:
        log_event(
            logger,
            'ERROR',
            'documents.storage_failed',
            source=source,
            attachment_id=attachment.pk,
            user_id=getattr(request.user, 'pk', None),
            operation='system_download',
            error_type=type(exc).__name__,
            outcome='failed',
            exc_info=True,
        )
        raise Http404('Attachment file is missing.') from exc

    log_event(
        logger,
        'INFO',
        'documents.system_downloaded',
        source=source,
        attachment_id=attachment.pk,
        user_id=getattr(request.user, 'pk', None),
        size_bytes=attachment.file_size,
        operation='system_download',
        outcome='ok',
    )
    return FileResponse(
        handle,
        as_attachment=True,
        filename=attachment.original_name,
        content_type=attachment.content_type or 'application/octet-stream',
    )


@login_required
def system_readonly(request, *args, **kwargs):
    """Every write against the «Вложения» branch, refused for every role.

    Registered on upload-, delete- and rename-shaped URLs so a direct attempt
    gets a 403 that means what it says, on GET as well as POST.
    `can_modify_system_attachments()` is the single answer, and it is False for
    administrators and superusers too: these files belong to the act, protocol
    or task that owns them, and to the quality history that records them.
    """
    if not can_modify_system_attachments(request.user):
        log_event(
            logger,
            'WARNING',
            'documents.system_modification_denied',
            source=kwargs.get('source', ''),
            user_id=getattr(request.user, 'pk', None),
            method=request.method,
            outcome='denied',
        )
        raise PermissionDenied(
            'Системные вложения доступны только для чтения. Файл изменяется там, '
            'где он был загружен.'
        )
    # Unreachable while the rule above holds. Left as an explicit branch
    # rather than as an assumption about it.
    raise Http404('No document matches the given query.')
