# Generated by Django 6.0.6 on 2026-09-02 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_smk_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmkSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('EXTERNAL_AUDIT', 'Внешний аудит'), ('INTERNAL_AUDIT', 'Внутренний аудит')], max_length=32, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_smk_sources', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Запись СМК',
                'verbose_name_plural': 'Записи СМК',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SmkNonConformity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Выявленное несоответствие')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_conformities', to='smk.smksource', verbose_name='Запись СМК')),
            ],
            options={
                'verbose_name': 'Выявленное несоответствие',
                'verbose_name_plural': 'Выявленные несоответствия',
                'ordering': ['display_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SmkCorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.TextField(verbose_name='Корректирующее мероприятие')),
                ('due_date', models.DateField(verbose_name='Срок')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='smk_actions', to='accounts.department', verbose_name='Подразделение')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='smk.smksource', verbose_name='Запись СМК')),
            ],
            options={
                'verbose_name': 'Корректирующее мероприятие',
                'verbose_name_plural': 'Корректирующие мероприятия',
                'ordering': ['display_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SmkActionAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='smk_action_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='smk.smkcorrectiveaction', verbose_name='Корректирующее мероприятие')),
            ],
            options={
                'verbose_name': 'Исполнитель мероприятия СМК',
                'verbose_name_plural': 'Исполнители мероприятий СМК',
                'constraints': [models.UniqueConstraint(fields=('action', 'user'), name='unique_smk_action_assignee')],
            },
        ),
    ]
