"""«Обязательно вложение» on an СМК корректирующее мероприятие.

One nullable-free boolean with `default=False`: every stored measure keeps the
permissive behaviour it was created under, and nothing is read, rewritten or
reclassified. The requirement itself is enforced only by
`tasks.services.complete_task()`, through the snapshot the task already carries
— no new validation path exists.
"""

# Generated by Django 6.0.6 on 2026-09-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smkcorrectiveaction',
            name='requires_attachment',
            field=models.BooleanField(default=False, verbose_name='Обязательно вложение'),
        ),
    ]
