"""«Дата аудита», and the finding a measure answers.

Two nullable columns and nothing else: no row is read, rewritten or
reclassified, and every record stored before this migration keeps a NULL in
both — which the page renders as «—» rather than inventing a date or a link.
`audit_date` is deliberately not backfilled from `created_at`: the two mean
different things, and guessing one from the other would be a fabricated fact.
"""

# Generated by Django 6.0.6 on 2026-09-02 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smk', '0002_corrective_action_requires_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='smkcorrectiveaction',
            name='non_conformity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_actions', to='smk.smknonconformity', verbose_name='Выявленное несоответствие'),
        ),
        migrations.AddField(
            model_name='smksource',
            name='audit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата аудита'),
        ),
    ]
