# Generated by Django 6.0.6 on 2026-09-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smk', '0006_backfill_smk_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='smkcorrectiveaction',
            name='superseded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заменено'),
        ),
        migrations.AddField(
            model_name='smknonconformity',
            name='superseded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заменено'),
        ),
    ]
