# Generated by Django 6.0.6 on 2026-09-10 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_department_roles'),
        ('smk', '0009_smk_source_archived_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='smksource',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='smk_sources', to='accounts.department', verbose_name='Отделение'),
        ),
    ]
