# Generated by Django 6.0.6 on 2026-09-10 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smk', '0010_smk_source_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smkcorrectiveaction',
            name='requires_attachment',
        ),
    ]
