# Generated by Django 6.0.6 on 2026-07-03 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Номер акта')),
                ('party_number', models.CharField(max_length=120, verbose_name='Номер партии')),
                ('nomenclature', models.CharField(max_length=240, verbose_name='Номенклатура')),
                ('description', models.TextField(verbose_name='Описание')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок рассмотрения')),
                ('ko_decision', models.CharField(blank=True, choices=[('ALLOW', 'Пропустить'), ('REJECT', 'Не пропускать'), ('RETURN', 'Вернуть на уточнение')], max_length=20, verbose_name='Решение КО')),
                ('ko_comment', models.TextField(blank=True, verbose_name='Комментарий КО')),
                ('ko_decision_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата решения КО')),
                ('to_root_cause', models.TextField(blank=True, verbose_name='Корневая причина')),
                ('to_action_summary', models.TextField(blank=True, verbose_name='Предлагаемые мероприятия')),
                ('to_analysis_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата анализа ТО')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_acts', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('defect_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.defecttype', verbose_name='Вид дефекта')),
                ('ko_decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ko_decided_acts', to=settings.AUTH_USER_MODEL, verbose_name='Решение КО внес')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.operation', verbose_name='Операция')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.priority', verbose_name='Приоритет')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.actstatus', verbose_name='Статус')),
                ('to_analysis_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_analyzed_acts', to=settings.AUTH_USER_MODEL, verbose_name='Анализ ТО внес')),
            ],
            options={
                'verbose_name': 'Акт',
                'verbose_name_plural': 'Акты',
                'ordering': ['-created_at'],
            },
        ),
    ]
