# Generated by Django 6.0.6 on 2026-07-07 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0001_initial'),
        ('references', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='acts.act', verbose_name='Акт')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='act_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Комментарий к акту',
                'verbose_name_plural': 'Комментарии к актам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActHistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Акт создан'), ('SENT_TO_KO', 'Акт передан в КО'), ('KO_DECISION_APPLIED', 'Решение КО внесено'), ('RETURNED_TO_OTK', 'Акт возвращён в ОТК'), ('SENT_TO_TO', 'Акт передан в ТО'), ('TO_ANALYSIS_APPLIED', 'Анализ ТО внесён'), ('COMMENT_ADDED', 'Комментарий добавлен')], max_length=40, verbose_name='Тип события')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='acts.act', verbose_name='Акт')),
                ('from_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='references.actstatus', verbose_name='Статус до')),
                ('to_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='references.actstatus', verbose_name='Статус после')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='act_history_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие истории акта',
                'verbose_name_plural': 'События истории актов',
                'ordering': ['-created_at'],
            },
        ),
    ]
