# Generated by Django 6.0.6 on 2026-07-07 07:54

import acts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0002_actcomment_acthistoryevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='acthistoryevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Акт создан'), ('SENT_TO_KO', 'Акт передан в КО'), ('KO_DECISION_APPLIED', 'Решение КО внесено'), ('RETURNED_TO_OTK', 'Акт возвращён в ОТК'), ('SENT_TO_TO', 'Акт передан в ТО'), ('TO_ANALYSIS_APPLIED', 'Анализ ТО внесён'), ('COMMENT_ADDED', 'Комментарий добавлен'), ('ATTACHMENT_ADDED', 'Вложение добавлено'), ('ATTACHMENT_DELETED', 'Вложение удалено')], max_length=40, verbose_name='Тип события'),
        ),
        migrations.CreateModel(
            name='ActAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=acts.models.act_attachment_upload_to, verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер файла')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='Тип содержимого')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='acts.act', verbose_name='Акт')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='act_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Вложение акта',
                'verbose_name_plural': 'Вложения актов',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
