# Generated by Django 6.0.6 on 2026-07-07 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0003_alter_acthistoryevent_event_type_actattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
        migrations.AddField(
            model_name='act',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_acts', to=settings.AUTH_USER_MODEL, verbose_name='Закрыл'),
        ),
        migrations.AddField(
            model_name='act',
            name='closing_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий закрытия'),
        ),
        migrations.AlterField(
            model_name='acthistoryevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Акт создан'), ('SENT_TO_KO', 'Акт передан в КО'), ('KO_DECISION_APPLIED', 'Решение КО внесено'), ('RETURNED_TO_OTK', 'Акт возвращён в ОТК'), ('SENT_TO_TO', 'Акт передан в ТО'), ('TO_ANALYSIS_APPLIED', 'Анализ ТО внесён'), ('COMMENT_ADDED', 'Комментарий добавлен'), ('ATTACHMENT_ADDED', 'Вложение добавлено'), ('ATTACHMENT_DELETED', 'Вложение удалено'), ('ACT_CLOSED', 'Акт закрыт')], max_length=40, verbose_name='Тип события'),
        ),
    ]
