# Generated by Django 6.0.6 on 2026-07-07 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0004_act_closed_at_act_closed_by_act_closing_comment_and_more'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='customer',
            field=models.CharField(blank=True, max_length=160, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='act',
            name='order_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='Номер заказа'),
        ),
        migrations.AddField(
            model_name='act',
            name='znp_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='Номер ЗНП'),
        ),
        migrations.CreateModel(
            name='ActDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание дефекта')),
                ('detected_at', models.DateField(verbose_name='Срок обнаружения несоответствия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='acts.act', verbose_name='Акт')),
                ('defect_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.defecttype', verbose_name='Вид дефекта')),
            ],
            options={
                'verbose_name': 'Дефект акта',
                'verbose_name_plural': 'Дефекты актов',
                'ordering': ['created_at'],
            },
        ),
    ]
