# Generated by Django 6.0.6 on 2026-07-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0005_act_customer_act_order_number_act_znp_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='ko_decision',
            field=models.CharField(blank=True, choices=[('ALLOW_NO_REWORK', 'Пропустить без доработок'), ('ALLOW_WITH_REWORK', 'Пропустить с доработками'), ('PROHIBIT_USE', 'Запретить использование'), ('ALLOW', 'Пропустить'), ('REJECT', 'Не пропускать'), ('RETURN', 'Вернуть на уточнение')], max_length=20, verbose_name='Решение КО'),
        ),
    ]
