# Generated by Django 6.0.6 on 2026-07-21 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0006_alter_act_ko_decision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actdefect',
            name='ko_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий КО'),
        ),
        migrations.AddField(
            model_name='actdefect',
            name='ko_decision',
            field=models.CharField(blank=True, choices=[('ALLOW_NO_REWORK', 'Пропустить без доработок'), ('ALLOW_WITH_REWORK', 'Пропустить с доработками'), ('PROHIBIT_USE', 'Запретить использование'), ('ALLOW', 'Пропустить'), ('REJECT', 'Не пропускать'), ('RETURN', 'Вернуть на уточнение')], max_length=20, verbose_name='Решение КО'),
        ),
        migrations.AddField(
            model_name='actdefect',
            name='ko_decision_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата решения КО'),
        ),
        migrations.AddField(
            model_name='actdefect',
            name='ko_decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ko_decided_defects', to=settings.AUTH_USER_MODEL, verbose_name='Решение КО внес'),
        ),
    ]
