# Generated by Django 6.0.6 on 2026-07-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0007_actdefect_ko_comment_actdefect_ko_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actdefect',
            name='checked_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Проверено продукции'),
        ),
        migrations.AddField(
            model_name='actdefect',
            name='nonconforming_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество несоответствующей продукции'),
        ),
        migrations.AlterField(
            model_name='actdefect',
            name='detected_at',
            field=models.DateField(verbose_name='Дата обнаружения несоответствия'),
        ),
    ]
