# Generated by Django 6.0.6 on 2026-07-22 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0008_actdefect_checked_quantity_and_more'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='kd_designation',
            field=models.CharField(blank=True, max_length=240, verbose_name='Обозначение по КД'),
        ),
        migrations.AddField(
            model_name='actdefect',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='references.operation', verbose_name='Операция'),
        ),
    ]
