# Generated by Django 6.0.6 on 2026-07-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0009_act_kd_designation_actdefect_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='actdefect',
            name='party_number',
            field=models.CharField(blank=True, max_length=120, verbose_name='Номер партии'),
        ),
        migrations.AddField(
            model_name='actdefect',
            name='znp_number',
            field=models.CharField(blank=True, max_length=80, verbose_name='Номер ЗНП'),
        ),
    ]
