# Generated by Django 6.0.6 on 2026-07-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0010_actdefect_party_number_actdefect_znp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='actdefect',
            name='mp_type',
            field=models.CharField(blank=True, choices=[('OL', 'ОЛ'), ('OLS', 'ОЛС'), ('OLR', 'ОЛР'), ('OLSR', 'ОЛСР'), ('PL', 'ПЛ'), ('PLS', 'ПЛС'), ('PLR', 'ПЛР'), ('PLSR', 'ПЛСР'), ('SL', 'ШЛ'), ('SLS', 'ШЛС'), ('SLR', 'ШЛР'), ('SLSR', 'ШЛСР'), ('TL', 'ТЛ'), ('TLS', 'ТЛС'), ('TLR', 'ТЛР'), ('TLSR', 'ТЛСР')], max_length=4, verbose_name='Тип МП'),
        ),
    ]
