# Generated by Django 6.0.6 on 2026-07-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0011_actdefect_mp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acthistoryevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Акт создан'), ('SENT_TO_KO', 'Акт передан в КО'), ('KO_DECISION_APPLIED', 'Решение КО внесено'), ('RETURNED_TO_OTK', 'Акт возвращён в ОТК'), ('SENT_TO_TO', 'Акт передан в ТО'), ('TO_ANALYSIS_APPLIED', 'Анализ ТО внесён'), ('COMMENT_ADDED', 'Комментарий добавлен'), ('ATTACHMENT_ADDED', 'Вложение добавлено'), ('ATTACHMENT_DELETED', 'Вложение удалено'), ('ACT_EDITED', 'Акт отредактирован'), ('ACT_CLOSED', 'Акт закрыт')], max_length=40, verbose_name='Тип события'),
        ),
    ]
