# Generated by Django 6.0.6 on 2026-07-23 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('acts', '0012_alter_acthistoryevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActRootAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_cause', models.TextField(verbose_name='Корневая причина')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_analyses', to='acts.act', verbose_name='Акт')),
            ],
            options={
                'verbose_name': 'Корневая проработка акта',
                'verbose_name_plural': 'Корневые проработки актов',
                'ordering': ['display_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ActCorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Корректирующее мероприятие')),
                ('due_date', models.DateField(verbose_name='Срок')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.department', verbose_name='Подразделение')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('root_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='acts.actrootanalysis', verbose_name='Корневая проработка')),
            ],
            options={
                'verbose_name': 'Корректирующее мероприятие',
                'verbose_name_plural': 'Корректирующие мероприятия',
                'ordering': ['display_order', 'pk'],
            },
        ),
    ]
