# Generated by Django 6.0.6 on 2026-07-23 08:59

from django.db import migrations, models


def add_otk_review_status(apps, schema_editor):
    ActStatus = apps.get_model('references', 'ActStatus')
    ActStatus.objects.update_or_create(
        code='OTK_REVIEW',
        defaults={
            'name': 'Проверка ОТК',
            'sort_order': 40,
            'is_final': False,
            'is_active': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0013_actrootanalysis_actcorrectiveaction'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_otk_review_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='acthistoryevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Акт создан'), ('SENT_TO_KO', 'Акт передан в КО'), ('KO_DECISION_APPLIED', 'Решение КО внесено'), ('RETURNED_TO_OTK', 'Акт возвращён в ОТК'), ('RETURNED_TO_KO', 'Акт возвращён в КО'), ('SENT_TO_TO', 'Акт передан в ТО'), ('TO_ANALYSIS_APPLIED', 'Анализ ТО внесён'), ('COMMENT_ADDED', 'Комментарий добавлен'), ('ATTACHMENT_ADDED', 'Вложение добавлено'), ('ATTACHMENT_DELETED', 'Вложение удалено'), ('ACT_EDITED', 'Акт отредактирован'), ('ACT_CLOSED', 'Акт закрыт')], max_length=40, verbose_name='Тип события'),
        ),
    ]
