# Generated by Django 6.0.6 on 2026-07-23 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_archived_status(apps, schema_editor):
    ActStatus = apps.get_model('references', 'ActStatus')
    ActStatus.objects.update_or_create(
        code='ARCHIVED',
        defaults={
            'name': 'Архивирован',
            'sort_order': 60,
            'is_final': True,
            'is_active': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0014_alter_acthistoryevent_event_type'),
        ('references', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(add_archived_status, migrations.RunPython.noop),
        migrations.AddField(
            model_name='act',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения'),
        ),
        migrations.AddField(
            model_name='act',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_acts', to=settings.AUTH_USER_MODEL, verbose_name='Утвердил'),
        ),
        migrations.AlterField(
            model_name='acthistoryevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Акт создан'), ('SENT_TO_KO', 'Акт передан в КО'), ('KO_DECISION_APPLIED', 'Решение КО внесено'), ('RETURNED_TO_OTK', 'Акт возвращён в ОТК'), ('RETURNED_TO_KO', 'Акт возвращён в КО'), ('RETURNED_TO_TO', 'Акт возвращён в ТО'), ('APPROVED', 'Акт утверждён'), ('SENT_TO_TO', 'Акт передан в ТО'), ('TO_ANALYSIS_APPLIED', 'Анализ ТО внесён'), ('COMMENT_ADDED', 'Комментарий добавлен'), ('ATTACHMENT_ADDED', 'Вложение добавлено'), ('ATTACHMENT_DELETED', 'Вложение удалено'), ('ACT_EDITED', 'Акт отредактирован'), ('ACT_CLOSED', 'Акт закрыт')], max_length=40, verbose_name='Тип события'),
        ),
    ]
