# Generated by Django 6.0.6 on 2026-07-24 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_responsible_to_assignees(apps, schema_editor):
    Action = apps.get_model('acts', 'ActCorrectiveAction')
    Assignee = apps.get_model('acts', 'ActCorrectiveActionAssignee')
    Assignee.objects.bulk_create([
        Assignee(corrective_action_id=action.pk, user_id=action.responsible_id)
        for action in Action.objects.exclude(responsible_id__isnull=True)
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0015_act_approved_at_act_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActCorrectiveActionAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrective_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='acts.actcorrectiveaction', verbose_name='Корректирующее мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Исполнитель корректирующего мероприятия',
                'verbose_name_plural': 'Исполнители корректирующих мероприятий',
                'constraints': [models.UniqueConstraint(fields=('corrective_action', 'user'), name='unique_corrective_action_assignee')],
            },
        ),
        migrations.RunPython(copy_responsible_to_assignees, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='actcorrectiveaction',
            name='responsible',
        ),
    ]
