# Generated by Django 6.0.6 on 2026-07-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0016_remove_actcorrectiveaction_responsible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='act_type',
            field=models.CharField(choices=[('OPERATIONAL_CONTROL', 'Операционный контроль'), ('INCOMING_CONTROL', 'Входной контроль')], default='OPERATIONAL_CONTROL', max_length=32, verbose_name='Тип акта'),
        ),
    ]
