# Generated by Django 6.0.6 on 2026-07-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0017_act_act_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='ko_decision',
            field=models.CharField(blank=True, choices=[('PROHIBIT_USE', 'Запретить использование'), ('ALLOW_NO_REWORK', 'Разрешить использование изделия с отклонением без доработки'), ('ALLOW_WITH_REWORK', 'Разрешить использование изделия с отклонением с доработкой'), ('ALLOW_NO_DEVIATION_REWORK', 'Разрешить использование изделия без отклонения с доработкой'), ('ALLOW', 'Пропустить'), ('REJECT', 'Не пропускать'), ('RETURN', 'Вернуть на уточнение')], max_length=32, verbose_name='Решение КО'),
        ),
        migrations.AlterField(
            model_name='actdefect',
            name='ko_decision',
            field=models.CharField(blank=True, choices=[('PROHIBIT_USE', 'Запретить использование'), ('ALLOW_NO_REWORK', 'Разрешить использование изделия с отклонением без доработки'), ('ALLOW_WITH_REWORK', 'Разрешить использование изделия с отклонением с доработкой'), ('ALLOW_NO_DEVIATION_REWORK', 'Разрешить использование изделия без отклонения с доработкой'), ('ALLOW', 'Пропустить'), ('REJECT', 'Не пропускать'), ('RETURN', 'Вернуть на уточнение')], max_length=32, verbose_name='Решение КО'),
        ),
    ]
