# Generated by Django 6.0.6 on 2026-08-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0018_alter_act_ko_decision_alter_actdefect_ko_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='actdefect',
            name='workshop',
            field=models.CharField(blank=True, choices=[('MP_SHOP', 'Цех МП'), ('TRANSFORMERS_SHOP', 'Цех трансформаторов')], max_length=32, verbose_name='Цех/поставщик'),
        ),
    ]
