# Generated by Django 6.0.6 on 2026-08-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0024_remove_act_defect_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='actcorrectiveaction',
            name='split_for_assignees',
            field=models.BooleanField(default=False, verbose_name='Разбить задачу для исполнителей'),
        ),
    ]
