# Generated by Django 6.0.6 on 2026-09-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0025_act_task_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='actcorrectiveaction',
            name='requires_attachment',
            field=models.BooleanField(default=False, verbose_name='Обязательно вложение'),
        ),
    ]
