# Generated by Django 6.0.6 on 2026-09-09 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acts', '0026_actcorrectiveaction_requires_attachment'),
        ('references', '0004_cancelled_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actdefect',
            name='quality_impact_assembly',
            field=models.BooleanField(default=False, verbose_name='Собираемость обеспечена'),
        ),
        migrations.AddField(
            model_name='actdefect',
            name='quality_impact_customer_agreed',
            field=models.BooleanField(default=False, verbose_name='Согласовано с заказчиком'),
        ),
        migrations.AddField(
            model_name='actdefect',
            name='quality_impact_em_parameters',
            field=models.BooleanField(default=False, verbose_name='Электромагнитные параметры проверены'),
        ),
        migrations.AddField(
            model_name='actdefect',
            name='quality_impact_em_tolerance',
            field=models.CharField(blank=True, max_length=200, verbose_name='Электромагнитные параметры, допуск по КД/ГОСТ'),
        ),
        migrations.AddField(
            model_name='actdefect',
            name='quality_impact_em_value',
            field=models.CharField(blank=True, max_length=200, verbose_name='Электромагнитные параметры, значение'),
        ),
        migrations.AddField(
            model_name='actdefect',
            name='quality_impact_insulation_margin',
            field=models.BooleanField(default=False, verbose_name='Расчетный запас по перегреву изоляции достаточен'),
        ),
        migrations.AddField(
            model_name='actdefect',
            name='quality_impact_no_interturn_short',
            field=models.BooleanField(default=False, verbose_name='Риск межвиткового замыкания исключен'),
        ),
        migrations.AddField(
            model_name='actdefect',
            name='quality_impact_other',
            field=models.BooleanField(default=False, verbose_name='Другое'),
        ),
        migrations.AddField(
            model_name='actdefect',
            name='quality_impact_other_text',
            field=models.TextField(blank=True, verbose_name='Другое, описание'),
        ),
        migrations.AddConstraint(
            model_name='actdefect',
            constraint=models.CheckConstraint(condition=models.Q(('quality_impact_em_parameters', True), models.Q(('quality_impact_em_tolerance', ''), ('quality_impact_em_value', '')), _connector='OR'), name='act_defect_em_values_only_when_checked'),
        ),
        migrations.AddConstraint(
            model_name='actdefect',
            constraint=models.CheckConstraint(condition=models.Q(('quality_impact_other', True), ('quality_impact_other_text', ''), _connector='OR'), name='act_defect_other_text_only_when_checked'),
        ),
    ]
