# Generated by Django 6.0.8 on 2026-09-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acts", "0027_act_defect_quality_impact"),
    ]

    operations = [
        migrations.AddField(
            model_name="acthistoryevent",
            name="substitution_note",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Основание (замещение)"
            ),
        ),
    ]
