# Generated by Django 6.0.8 on 2026-09-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acts", "0028_history_substitution_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="act",
            name="ko_round",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Раунд решения КО"
            ),
        ),
        migrations.AddField(
            model_name="actdefect",
            name="ko_round",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Раунд решения КО"
            ),
        ),
    ]
