# Generated by Django 6.0.6 on 2026-08-19 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_pdo_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Тип протокола',
                'verbose_name_plural': 'Типы протоколов',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('APPROVAL', 'На согласовании'), ('REVISION', 'На доработке'), ('ARCHIVED', 'В архиве')], default='DRAFT', max_length=16, verbose_name='Статус')),
                ('revision', models.PositiveIntegerField(default=0, verbose_name='Редакция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_protocols', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('protocol_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocols', to='protocols.protocoltype', verbose_name='Тип протокола')),
            ],
            options={
                'verbose_name': 'Протокол',
                'verbose_name_plural': 'Протоколы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.TextField(verbose_name='Задача')),
                ('due_date', models.DateField(verbose_name='Срок')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocol_actions', to='accounts.department', verbose_name='Подразделение')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='protocols.protocol', verbose_name='Протокол')),
            ],
            options={
                'verbose_name': 'Задача протокола',
                'verbose_name_plural': 'Задачи протоколов',
                'ordering': ['display_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolAgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Вопрос повестки')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='protocols.protocol', verbose_name='Протокол')),
            ],
            options={
                'verbose_name': 'Вопрос повестки',
                'verbose_name_plural': 'Вопросы повестки',
                'ordering': ['display_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolHistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Протокол создан'), ('EDITED', 'Протокол отредактирован'), ('SENT_FOR_APPROVAL', 'Протокол отправлен на согласование'), ('APPROVED_BY_USER', 'Участник согласовал протокол'), ('RETURNED_FOR_REVISION', 'Протокол возвращён на доработку'), ('RESENT_FOR_APPROVAL', 'Протокол повторно отправлен на согласование'), ('ARCHIVED', 'Протокол помещён в архив'), ('TASKS_CREATED', 'Задачи созданы')], max_length=40, verbose_name='Тип события')),
                ('revision', models.PositiveIntegerField(default=0, verbose_name='Редакция')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_history_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='protocols.protocol', verbose_name='Протокол')),
            ],
            options={
                'verbose_name': 'Событие истории протокола',
                'verbose_name_plural': 'События истории протоколов',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Требуется согласование')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('display_name', models.CharField(max_length=180, verbose_name='ФИО в документе')),
                ('position', models.CharField(blank=True, max_length=120, verbose_name='Должность в документе')),
                ('department_name', models.CharField(blank=True, max_length=120, verbose_name='Подразделение в документе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protocol_participations', to='accounts.department', verbose_name='Подразделение')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='protocols.protocol', verbose_name='Протокол')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocol_participations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник протокола',
                'verbose_name_plural': 'Участники протоколов',
                'ordering': ['display_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Слушали')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='protocols.protocol', verbose_name='Протокол')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='speeches', to='protocols.protocolparticipant', verbose_name='Выступающий')),
            ],
            options={
                'verbose_name': 'Выступление',
                'verbose_name_plural': 'Выступления',
                'ordering': ['display_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolActionAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='protocols.protocolaction', verbose_name='Задача протокола')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocol_action_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Исполнитель задачи протокола',
                'verbose_name_plural': 'Исполнители задач протоколов',
                'constraints': [models.UniqueConstraint(fields=('action', 'user'), name='unique_protocol_action_assignee')],
            },
        ),
        migrations.AddConstraint(
            model_name='protocolparticipant',
            constraint=models.UniqueConstraint(fields=('protocol', 'user'), name='unique_protocol_participant'),
        ),
        migrations.AddConstraint(
            model_name='protocol',
            constraint=models.UniqueConstraint(fields=('protocol_type', 'number'), name='unique_protocol_number_per_type'),
        ),
    ]
