# Generated by Django 6.0.6 on 2026-08-20 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0002_quality_protocol_type'),
        ('tasks', '0008_task_source_shape_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(verbose_name='Редакция')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает согласования'), ('APPROVED', 'Согласовано'), ('RETURNED', 'Возвращено на доработку'), ('CANCELLED', 'Отменено')], default='PENDING', max_length=16, verbose_name='Статус')),
                ('required_as_participant', models.BooleanField(default=False, verbose_name='Согласует как участник')),
                ('required_as_action_assignee', models.BooleanField(default=False, verbose_name='Согласует как исполнитель задачи')),
                ('display_name', models.CharField(max_length=180, verbose_name='ФИО в документе')),
                ('position', models.CharField(blank=True, max_length=120, verbose_name='Должность в документе')),
                ('department_name', models.CharField(blank=True, max_length=120, verbose_name='Подразделение в документе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Решение принято')),
                ('return_comment', models.TextField(blank=True, verbose_name='Комментарий возврата')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='protocols.protocol', verbose_name='Протокол')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_approval', to='tasks.task', verbose_name='Задача согласования')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocol_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Согласующий')),
            ],
            options={
                'verbose_name': 'Согласование протокола',
                'verbose_name_plural': 'Согласования протоколов',
                'ordering': ['-revision', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('protocol', 'revision', 'user'), name='unique_protocol_approval_per_revision')],
            },
        ),
    ]
