# Generated by Django 6.0.6 on 2026-08-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0003_protocolapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolaction',
            name='split_for_assignees',
            field=models.BooleanField(default=False, verbose_name='Разбить задачу для участников'),
        ),
    ]
