# Generated by Django 6.0.6 on 2026-08-25 05:43

import django.db.models.deletion
import protocols.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0004_protocolaction_split_for_assignees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolhistoryevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Протокол создан'), ('EDITED', 'Протокол отредактирован'), ('SENT_FOR_APPROVAL', 'Протокол отправлен на согласование'), ('APPROVED_BY_USER', 'Участник согласовал протокол'), ('RETURNED_FOR_REVISION', 'Протокол возвращён на доработку'), ('RESENT_FOR_APPROVAL', 'Протокол повторно отправлен на согласование'), ('ARCHIVED', 'Протокол помещён в архив'), ('TASKS_CREATED', 'Задачи созданы'), ('COMMENT_ADDED', 'Добавлен комментарий'), ('ATTACHMENT_ADDED', 'Добавлено вложение'), ('ATTACHMENT_DELETED', 'Вложение удалено')], max_length=40, verbose_name='Тип события'),
        ),
        migrations.CreateModel(
            name='ProtocolAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=protocols.models.protocol_attachment_upload_to, verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер файла')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='Тип содержимого')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='protocols.protocol', verbose_name='Протокол')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Вложение протокола',
                'verbose_name_plural': 'Вложения протоколов',
                'ordering': ['-uploaded_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='protocols.protocol', verbose_name='Протокол')),
            ],
            options={
                'verbose_name': 'Комментарий к протоколу',
                'verbose_name_plural': 'Комментарии к протоколам',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
