# Generated by Django 6.0.6 on 2026-09-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_mas_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('otk', 'ОТК'), ('ko', 'КО'), ('to', 'ТО'), ('pdo', 'ПДО'), ('mas', 'Мастер производства'), ('smk', 'СМК'), ('manager', 'Руководитель'), ('admin', 'Администратор')], default='otk', max_length=20, verbose_name='Роль'),
        ),
    ]
