# Generated by Django 6.0.6 on 2026-09-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_organisational_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_bug_responsible',
            field=models.BooleanField(default=False, verbose_name='Ответственный за ошибки'),
        ),
    ]
