# Generated by Django 6.0.6 on 2026-09-10 09:48

"""Three more `UserProfile.Role` values: Мастер ПиР, Мастер МП и РЛ, Мастер ТР.

A `choices` change and nothing else, exactly like `0010`: no column is altered,
no row is touched, and every existing profile keeps its stored value —
including the `'mas'` of anybody filed under «Мастера производства» before the
split. That value stays in `choices` on purpose; a role is retired by not being
offered, never by being removed under the rows that hold it.

The roles grant nothing. No permission module gained a branch for them: they
read what any authenticated user reads and complete the tasks assigned to them
personally, which is `TaskAssignee`'s answer rather than a role's. They are the
person's title beside `accounts.0012`'s three departments, which are where that
person works.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_production_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('otk', 'ОТК'), ('ko', 'КО'), ('to', 'ТО'), ('pdo', 'ПДО'), ('mas', 'Мастер производства'), ('mas_pir', 'Мастер ПиР'), ('mas_mp_rl', 'Мастер МП и РЛ'), ('mas_tr', 'Мастер ТР'), ('smk', 'СМК'), ('opr', 'Отдел продаж'), ('ozk', 'Отдел закупок'), ('lab', 'Лаборатория'), ('skl', 'Склад'), ('feo', 'ФЭО'), ('manager', 'Руководитель'), ('admin', 'Администратор')], default='otk', max_length=20, verbose_name='Роль'),
        ),
    ]
