# Generated by Django 6.0.8 on 2026-09-25 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_production_roles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleSubstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("otk", "ОТК"),
                            ("ko", "КО"),
                            ("to", "ТО"),
                            ("pdo", "ПДО"),
                            ("mas", "Мастер производства"),
                            ("mas_pir", "Мастер ПиР"),
                            ("mas_mp_rl", "Мастер МП и РЛ"),
                            ("mas_tr", "Мастер ТР"),
                            ("smk", "СМК"),
                            ("opr", "Отдел продаж"),
                            ("ozk", "Отдел закупок"),
                            ("lab", "Лаборатория"),
                            ("skl", "Склад"),
                            ("feo", "ФЭО"),
                            ("manager", "Руководитель"),
                        ],
                        max_length=20,
                        verbose_name="Дополнительная роль",
                    ),
                ),
                ("date_from", models.DateField(verbose_name="С")),
                ("date_to", models.DateField(verbose_name="По (включительно)")),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Основание"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто назначил",
                    ),
                ),
                (
                    "substitutes_for",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="substituted_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Замещает",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_substitutions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Замещение (дополнительная роль)",
                "verbose_name_plural": "Замещения (дополнительные роли)",
                "ordering": ["-date_from", "pk"],
                "indexes": [
                    models.Index(
                        fields=["user", "date_from", "date_to"],
                        name="role_subst_user_dates",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("date_to__gte", models.F("date_from"))),
                        name="role_substitution_period_is_ordered",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("role", "admin"), _negated=True),
                        name="role_substitution_never_admin",
                    ),
                ],
            },
        ),
    ]
