# Generated by Django 6.0.8 on 2026-09-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_role_substitution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolesubstitution",
            name="role",
            field=models.CharField(
                choices=[
                    ("otk", "ОТК"),
                    ("ko_mp", "КО МП"),
                    ("ko_tr", "КО ТР"),
                    ("ko_pir", "КО ЦПиР"),
                    ("to", "ТО"),
                    ("pdo", "ПДО"),
                    ("mas_pir", "Мастер ПиР"),
                    ("mas_mp_rl", "Мастер МП и РЛ"),
                    ("mas_tr", "Мастер ТР"),
                    ("smk", "СМК"),
                    ("opr", "Отдел продаж"),
                    ("ozk", "Отдел закупок"),
                    ("lab", "Лаборатория"),
                    ("skl", "Склад"),
                    ("feo", "ФЭО"),
                    ("manager", "Руководитель"),
                ],
                max_length=20,
                verbose_name="Дополнительная роль",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("otk", "ОТК"),
                    ("ko", "КО"),
                    ("ko_mp", "КО МП"),
                    ("ko_tr", "КО ТР"),
                    ("ko_pir", "КО ЦПиР"),
                    ("to", "ТО"),
                    ("pdo", "ПДО"),
                    ("mas", "Мастер производства"),
                    ("mas_pir", "Мастер ПиР"),
                    ("mas_mp_rl", "Мастер МП и РЛ"),
                    ("mas_tr", "Мастер ТР"),
                    ("smk", "СМК"),
                    ("opr", "Отдел продаж"),
                    ("ozk", "Отдел закупок"),
                    ("lab", "Лаборатория"),
                    ("skl", "Склад"),
                    ("feo", "ФЭО"),
                    ("manager", "Руководитель"),
                    ("admin", "Администратор"),
                ],
                default="otk",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
    ]
