# Generated by Django 6.0.8 on 2026-09-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_workshop_ko_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_document_responsible",
            field=models.BooleanField(
                default=False, verbose_name="Ответственный за документацию"
            ),
        ),
    ]
