# Generated by Django 6.0.6 on 2026-09-02 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_drop_file_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='documents.document', verbose_name='Документ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранный документ',
                'verbose_name_plural': 'Избранные документы',
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('user', 'document'), name='documents_favorite_unique_per_user')],
            },
        ),
    ]
