# Generated by Django 6.0.8 on 2026-09-25 05:21

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_userprofile_is_document_responsible"),
        ("acts", "0030_open_ko_round_for_acts_in_review"),
        ("documents", "0007_document_favorites"),
        ("protocols", "0007_web_system_protocol_type"),
        ("tasks", "0018_bug_report_task"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "base_manager_name": "all_objects",
                "ordering": ["name", "pk"],
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
            },
        ),
        migrations.AlterModelManagers(
            name="document",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="document",
            name="cancellation_reason",
            field=models.TextField(blank=True, verbose_name="Причина отмены"),
        ),
        migrations.AddField(
            model_name="document",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Отменён"),
        ),
        migrations.AddField(
            model_name="document",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отменил",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="В корзине с"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trashed_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отправил в корзину",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="designation",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Обозначение"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="effective_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата введения"),
        ),
        migrations.AddField(
            model_name="document",
            name="owner_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_documents",
                to="accounts.department",
                verbose_name="Подразделение-владелец",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsible_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ответственный",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="review_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата пересмотра"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Проект"),
                    ("ACTIVE", "Действующий"),
                    ("CANCELLED", "Отменён"),
                ],
                default="ACTIVE",
                max_length=16,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="documentfolder",
            name="allowed_roles",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Доступ только для ролей"
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="ack_department_ids",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Ознакомить подразделения"
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="ack_roles",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Ознакомить роли"
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="approval_comment",
            field=models.TextField(blank=True, verbose_name="Причина возврата"),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="approval_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Без согласования"),
                    ("PENDING", "На согласовании"),
                    ("APPROVED", "Согласована"),
                    ("RETURNED", "Возвращена"),
                ],
                default="",
                max_length=16,
                verbose_name="Согласование",
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="revision_label",
            field=models.CharField(blank=True, max_length=40, verbose_name="Изменение"),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="text_content",
            field=models.TextField(blank=True, verbose_name="Текст документа"),
        ),
        migrations.AlterField(
            model_name="documenthistoryevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("DOCUMENT_CREATED", "Документ создан"),
                    ("VERSION_ADDED", "Загружена версия"),
                    ("VERSION_RESTORED", "Версия восстановлена"),
                    ("DOCUMENT_DELETED", "Документ удалён"),
                    ("CARD_UPDATED", "Изменена карточка"),
                    ("MOVED", "Перенесён"),
                    ("TRASHED", "Отправлен в корзину"),
                    ("RESTORED", "Восстановлен из корзины"),
                    ("STATUS_CHANGED", "Изменён статус"),
                    ("VERSION_SUBMITTED", "Версия отправлена на согласование"),
                    ("VERSION_APPROVED", "Версия согласована"),
                    ("VERSION_RETURNED", "Версия возвращена"),
                    ("ACK_REQUESTED", "Разослан на ознакомление"),
                    ("LINKED", "Связан с документом системы"),
                    ("UNLINKED", "Связь удалена"),
                ],
                max_length=32,
                verbose_name="Событие",
            ),
        ),
        migrations.CreateModel(
            name="DocumentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлена"),
                ),
                (
                    "act",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_links",
                        to="acts.act",
                        verbose_name="Акт",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Добавил",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="documents.document",
                        verbose_name="Документ",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_links",
                        to="protocols.protocol",
                        verbose_name="Протокол",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка на документ",
                "verbose_name_plural": "Ссылки на документы",
                "ordering": ["-created_at", "-pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("act__isnull", False), ("protocol__isnull", True)
                            ),
                            models.Q(
                                ("act__isnull", True), ("protocol__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="documents_link_exactly_one_target",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("act__isnull", False)),
                        fields=("document", "act"),
                        name="documents_link_unique_act",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("protocol__isnull", False)),
                        fields=("document", "protocol"),
                        name="documents_link_unique_protocol",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="documents.document",
                        verbose_name="Документ",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="documents.documentfolder",
                        verbose_name="Папка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка на документы",
                "verbose_name_plural": "Подписки на документы",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("document__isnull", False), ("folder__isnull", True)
                            ),
                            models.Q(
                                ("document__isnull", True), ("folder__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="documents_subscription_exactly_one_target",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("document__isnull", False)),
                        fields=("user", "document"),
                        name="documents_subscription_unique_document",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("folder__isnull", False)),
                        fields=("user", "folder"),
                        name="documents_subscription_unique_folder",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentVersionApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Ожидает"),
                            ("APPROVED", "Согласовано"),
                            ("RETURNED", "Возвращено"),
                            ("CANCELLED", "Отменено"),
                        ],
                        default="PENDING",
                        max_length=16,
                        verbose_name="Решение",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Решение принято"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_approval",
                        to="tasks.task",
                        verbose_name="Задача согласования",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Согласующий",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="documents.documentversion",
                        verbose_name="Версия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Согласование версии",
                "verbose_name_plural": "Согласования версий",
                "ordering": ["pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("version", "user"),
                        name="documents_approval_unique_per_user",
                    )
                ],
            },
        ),
    ]
