"""
Django settings for ecosystem project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ib1ihuw1mz&*aj!efa@^gj$(4#bgqo-fp*jwf^n7m9kunfw+gx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'dashboard',
    'accounts',
    'references',
    'acts',
    'tasks',
    'notifications',
    'maintenance',
    'realtime',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecosystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.notification_summary',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecosystem.wsgi.application'
# The SSE stream is an async view and needs a long-lived ASGI connection; the
# rest of the project keeps working unchanged under WSGI.
ASGI_APPLICATION = 'ecosystem.asgi.application'


# Environment variable helpers
#
# Compact readers shared by every environment-driven setting below (database,
# email). Errors are raised as ImproperlyConfigured so misconfiguration fails
# loudly at startup instead of silently falling back to a default.

def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_int(name, default):
    value = os.getenv(name)
    if not value:
        return default
    try:
        return int(value)
    except ValueError as exc:
        raise ImproperlyConfigured(
            f'Environment variable "{name}" must be an integer; got "{value}".'
        ) from exc


def env_str_required(name):
    value = os.getenv(name)
    if value is None or not value.strip():
        raise ImproperlyConfigured(f'Environment variable "{name}" is required but not set.')
    return value


def env_number(name, default, *, minimum, maximum, cast=float):
    """Read a positive number and refuse values outside a sensible range.

    Used by the real-time timing settings, where a zero or absurd value would
    produce a busy loop or an effectively dead stream instead of a clear error.
    """
    raw = os.getenv(name)
    if raw is None or not raw.strip():
        value = cast(default)
    else:
        try:
            value = cast(raw.strip())
        except (TypeError, ValueError) as exc:
            raise ImproperlyConfigured(
                f'Environment variable "{name}" must be a number; got "{raw}".'
            ) from exc
    if value <= 0:
        raise ImproperlyConfigured(f'Environment variable "{name}" must be positive; got {value}.')
    if not minimum <= value <= maximum:
        raise ImproperlyConfigured(
            f'Environment variable "{name}" must be between {minimum} and {maximum}; got {value}.'
        )
    return value


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# DATABASE_ENGINE selects the backend: "sqlite" (default, no extra
# configuration required) or "postgresql" (requires DB_NAME, DB_USER, and
# DB_PASSWORD; see docs/postgresql_preparation.md). There is no hidden
# fallback to SQLite if PostgreSQL is selected but misconfigured.

DATABASE_ENGINE = os.getenv('DATABASE_ENGINE', 'sqlite').strip().lower()


def _resolve_sqlite_path():
    """Return the SQLite file to use, honouring the optional SQLITE_DB_PATH.

    Defaults to the existing `BASE_DIR / "db.sqlite3"`. A relative override is
    resolved against BASE_DIR. This exists so a *copy* of the database can be
    exported by the maintenance commands without swapping the working file.
    """
    raw = os.getenv('SQLITE_DB_PATH', '').strip()
    if not raw:
        return BASE_DIR / 'db.sqlite3'
    candidate = Path(raw).expanduser()
    return candidate if candidate.is_absolute() else (BASE_DIR / candidate).resolve()


if DATABASE_ENGINE == 'sqlite':
    SQLITE_DB_PATH = _resolve_sqlite_path()
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': SQLITE_DB_PATH,
        }
    }
elif DATABASE_ENGINE == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env_str_required('DB_NAME'),
            'USER': env_str_required('DB_USER'),
            'PASSWORD': env_str_required('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': env_int('DB_PORT', 5432),
            'CONN_MAX_AGE': env_int('DB_CONN_MAX_AGE', 0),
            'CONN_HEALTH_CHECKS': env_bool('DB_CONN_HEALTH_CHECKS', False),
        }
    }
else:
    raise ImproperlyConfigured(
        f'Unsupported DATABASE_ENGINE "{DATABASE_ENGINE}". Supported values: sqlite, postgresql.'
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Asia/Yekaterinburg'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = 'media/'


def _resolve_media_root():
    """Return the media directory, honouring the optional MEDIA_ROOT_PATH.

    Defaults to the existing `BASE_DIR / "media"`. A relative override is
    resolved against BASE_DIR. This exists so a rehearsal can import a bundle
    into a *separate* target media directory without touching the working one.
    """
    raw = os.getenv('MEDIA_ROOT_PATH', '').strip()
    if not raw:
        return BASE_DIR / 'media'
    candidate = Path(raw).expanduser()
    return candidate if candidate.is_absolute() else (BASE_DIR / candidate).resolve()


MEDIA_ROOT = _resolve_media_root()

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'dashboard:home'
LOGOUT_REDIRECT_URL = 'accounts:login'


# Email notifications are deliberately disabled by default. SMTP credentials are
# read only from the deployment environment and must never be committed.
EMAIL_NOTIFICATIONS_ENABLED = env_bool('EMAIL_NOTIFICATIONS_ENABLED', False)
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
APP_BASE_URL = os.getenv('APP_BASE_URL', 'http://127.0.0.1:8000')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'quality-ecosystem@localhost')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = env_int('EMAIL_PORT', 25)
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', False)
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', False)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_TIMEOUT = env_int('EMAIL_TIMEOUT', 10)
EMAIL_NOTIFICATION_MAX_ATTEMPTS = env_int('EMAIL_NOTIFICATION_MAX_ATTEMPTS', 3)
EMAIL_NOTIFICATION_RETRY_DELAY_SECONDS = env_int('EMAIL_NOTIFICATION_RETRY_DELAY_SECONDS', 300)
EMAIL_NOTIFICATION_BATCH_SIZE = env_int('EMAIL_NOTIFICATION_BATCH_SIZE', 100)
EMAIL_NOTIFICATION_PROCESSING_TIMEOUT_SECONDS = env_int(
    'EMAIL_NOTIFICATION_PROCESSING_TIMEOUT_SECONDS',
    900,
)


# Real-time events (RT-1: contract only, no transport)
#
# Disabled by default: with REALTIME_ENABLED=false the emitters return before
# resolving any recipient, so no extra query runs and the project behaves
# exactly as it did before the `realtime` app existed. The default backend
# sends nothing; a Redis/SSE backend is an RT-2 concern and is configured by
# pointing REALTIME_PUBLISHER_BACKEND at it — business code never changes.
REALTIME_ENABLED = env_bool('REALTIME_ENABLED', False)
REALTIME_PUBLISHER_BACKEND = os.getenv(
    'REALTIME_PUBLISHER_BACKEND',
    'realtime.backends.NoopRealtimePublisher',
)
# A publisher failure happens after the business transaction is committed, so
# by default it is logged and swallowed. Set to false in a test or diagnostic
# environment to let the exception surface.
REALTIME_FAIL_SILENTLY = env_bool('REALTIME_FAIL_SILENTLY', True)

# Redis transport (RT-2). Nothing here is read while REALTIME_ENABLED=false and
# the Noop publisher is selected: no client is built and no connection is made,
# so `manage.py check` and an ordinary run need no Redis server at all.
REALTIME_REDIS_URL = os.getenv('REALTIME_REDIS_URL', 'redis://127.0.0.1:6379/0')
# Namespace for every Pub/Sub channel: `<prefix>:<target.key>`.
REALTIME_CHANNEL_PREFIX = os.getenv('REALTIME_CHANNEL_PREFIX', 'quality-ecosystem:realtime')
REALTIME_REDIS_CONNECT_TIMEOUT_SECONDS = env_number(
    'REALTIME_REDIS_CONNECT_TIMEOUT_SECONDS', 5.0, minimum=0.1, maximum=60.0
)
REALTIME_REDIS_SOCKET_TIMEOUT_SECONDS = env_number(
    'REALTIME_REDIS_SOCKET_TIMEOUT_SECONDS', 5.0, minimum=0.1, maximum=60.0
)
# Silence between events after which the stream emits an SSE comment, so proxies
# and clients can tell a live connection from a dead one.
REALTIME_HEARTBEAT_SECONDS = env_number(
    'REALTIME_HEARTBEAT_SECONDS', 25.0, minimum=1.0, maximum=300.0
)
# Reconnect delay advertised to the client in the initial `retry:` frame.
REALTIME_RECONNECT_DELAY_MS = env_number(
    'REALTIME_RECONNECT_DELAY_MS', 3000, minimum=100, maximum=300000, cast=int
)
# Hard ceiling for one serialized event, enforced before publishing and again
# before writing to the stream.
REALTIME_MAX_EVENT_BYTES = env_number(
    'REALTIME_MAX_EVENT_BYTES', 16384, minimum=256, maximum=1048576, cast=int
)


# Only the `realtime` logger is configured here; Django's own defaults are
# preserved because `disable_existing_loggers` stays false.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'realtime': {'format': '[%(asctime)s] %(levelname)s %(name)s: %(message)s'},
    },
    'handlers': {
        'realtime_console': {
            'class': 'logging.StreamHandler',
            'formatter': 'realtime',
        },
    },
    'loggers': {
        'realtime': {
            'handlers': ['realtime_console'],
            'level': os.getenv('REALTIME_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}
