"""
Django settings for ecosystem project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlsplit

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# --------------------------------------------------------------------------
# Environment mode
#
# `APP_ENV` is the single explicit switch between a convenient local setup and
# a locked-down deployment. Nothing is inferred from DEBUG or from the presence
# of a variable: production behaviour is opt-in and unambiguous, and an
# unknown value is refused rather than silently treated as development.
# --------------------------------------------------------------------------

DEVELOPMENT = 'development'
TEST = 'test'
PRODUCTION = 'production'
VALID_APP_ENVS = (DEVELOPMENT, TEST, PRODUCTION)

APP_ENV = os.getenv('APP_ENV', DEVELOPMENT).strip().lower() or DEVELOPMENT
if APP_ENV not in VALID_APP_ENVS:
    raise ImproperlyConfigured(
        f'Unsupported APP_ENV "{APP_ENV}". Supported values: {", ".join(VALID_APP_ENVS)}.'
    )

IS_DEVELOPMENT = APP_ENV == DEVELOPMENT
IS_TEST = APP_ENV == TEST
IS_PRODUCTION = APP_ENV == PRODUCTION


# Application definition

INSTALLED_APPS = [
    # The project package itself: no models, only the deployment system checks.
    'ecosystem',
    'dashboard',
    'accounts',
    'references',
    'acts',
    'tasks',
    'notifications',
    'maintenance',
    'realtime',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # After AuthenticationMiddleware on purpose: it needs a resolvable
    # `request.user` to record a user id, and it must wrap the view so it can
    # time the request and catch an exception on the way out.
    'ecosystem.middleware.RequestLoggingMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecosystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.notification_summary',
                'realtime.context_processors.realtime_client_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecosystem.wsgi.application'
# The SSE stream is an async view and needs a long-lived ASGI connection; the
# rest of the project keeps working unchanged under WSGI.
ASGI_APPLICATION = 'ecosystem.asgi.application'


# Environment variable helpers
#
# Compact readers shared by every environment-driven setting below (database,
# email). Errors are raised as ImproperlyConfigured so misconfiguration fails
# loudly at startup instead of silently falling back to a default.

def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_int(name, default):
    value = os.getenv(name)
    if not value:
        return default
    try:
        return int(value)
    except ValueError as exc:
        raise ImproperlyConfigured(
            f'Environment variable "{name}" must be an integer; got "{value}".'
        ) from exc


def env_str_required(name):
    value = os.getenv(name)
    if value is None or not value.strip():
        raise ImproperlyConfigured(f'Environment variable "{name}" is required but not set.')
    return value


def env_number(name, default, *, minimum, maximum, cast=float):
    """Read a positive number and refuse values outside a sensible range.

    Used by the real-time timing settings, where a zero or absurd value would
    produce a busy loop or an effectively dead stream instead of a clear error.
    """
    raw = os.getenv(name)
    if raw is None or not raw.strip():
        value = cast(default)
    else:
        try:
            value = cast(raw.strip())
        except (TypeError, ValueError) as exc:
            raise ImproperlyConfigured(
                f'Environment variable "{name}" must be a number; got "{raw}".'
            ) from exc
    if value <= 0:
        raise ImproperlyConfigured(f'Environment variable "{name}" must be positive; got {value}.')
    if not minimum <= value <= maximum:
        raise ImproperlyConfigured(
            f'Environment variable "{name}" must be between {minimum} and {maximum}; got {value}.'
        )
    return value


def env_list(name, default=()):
    """Read a comma-separated list: trimmed, de-duplicated, order preserved.

    An empty element is dropped rather than becoming an empty host or origin,
    which would otherwise silently match nothing (or, for ALLOWED_HOSTS, look
    configured while being useless).
    """
    raw = os.getenv(name)
    if raw is None:
        return list(default)
    items = []
    for chunk in raw.split(','):
        value = chunk.strip()
        if value and value not in items:
            items.append(value)
    return items


def env_timeout_ms(name, default, *, maximum=3_600_000):
    """A millisecond timeout: a non-negative integer, `0` meaning disabled."""
    raw = os.getenv(name)
    if raw is None or not raw.strip():
        value = int(default)
    else:
        try:
            value = int(raw.strip())
        except (TypeError, ValueError) as exc:
            raise ImproperlyConfigured(
                f'Environment variable "{name}" must be an integer number of '
                f'milliseconds; got "{raw}".'
            ) from exc
    if value < 0:
        raise ImproperlyConfigured(
            f'Environment variable "{name}" must not be negative; got {value}. '
            'Use 0 to disable the timeout.'
        )
    if value > maximum:
        raise ImproperlyConfigured(
            f'Environment variable "{name}" must not exceed {maximum} ms; got {value}.'
        )
    return value


def env_path(name, default):
    """A filesystem path from the environment; relative resolves against BASE_DIR."""
    raw = os.getenv(name, '').strip()
    if not raw:
        return default
    candidate = Path(raw).expanduser()
    return candidate if candidate.is_absolute() else (BASE_DIR / candidate).resolve()


def _require_https_url(value, name):
    """Refuse anything that is not an absolute `https://` URL."""
    parts = urlsplit(value)
    if parts.scheme != 'https' or not parts.netloc:
        raise ImproperlyConfigured(
            f'{name} must be an absolute https:// URL when APP_ENV=production; '
            f'got scheme "{parts.scheme or "(none)"}".'
        )
    return value


# --------------------------------------------------------------------------
# Core Django settings
#
# Every one of these is environment-driven. In development they keep working
# defaults so a fresh clone runs with no configuration at all; in production
# each is validated at import time, so a misconfiguration stops the process at
# startup instead of surfacing on the first user request.
# --------------------------------------------------------------------------

# The key committed for local development. Publicly known by definition — it is
# in Git — so production must never use it.
DEVELOPMENT_SECRET_KEY = 'django-insecure-ib1ihuw1mz&*aj!efa@^gj$(4#bgqo-fp*jwf^n7m9kunfw+gx'
MIN_SECRET_KEY_LENGTH = 50
# Obvious placeholders somebody might paste in "just to get it running".
UNSAFE_SECRET_KEY_VALUES = frozenset(
    {'changeme', 'change-me', 'secret', 'secret-key', 'password', 'test', 'insecure', 'todo'}
)


def _resolve_secret_key():
    """Return the signing key.

    The key itself is never included in any error message or log line: a
    misconfiguration report must describe the *problem*, never echo the value
    it was given.
    """
    raw = os.getenv('SECRET_KEY', '').strip()
    if not IS_PRODUCTION:
        return raw or DEVELOPMENT_SECRET_KEY
    if not raw:
        raise ImproperlyConfigured(
            'SECRET_KEY is required when APP_ENV=production and must come from '
            'the deployment environment.'
        )
    if raw == DEVELOPMENT_SECRET_KEY or raw.startswith('django-insecure-'):
        raise ImproperlyConfigured(
            'SECRET_KEY is the published development key. It is committed to '
            'Git and therefore public; generate a fresh key for production.'
        )
    # Placeholder before length: a placeholder is almost always short too, and
    # "this is a placeholder" is the more useful of the two messages.
    if raw.lower() in UNSAFE_SECRET_KEY_VALUES:
        raise ImproperlyConfigured(
            'SECRET_KEY is an obvious placeholder value; generate a real key.'
        )
    if len(raw) < MIN_SECRET_KEY_LENGTH:
        raise ImproperlyConfigured(
            f'SECRET_KEY must be at least {MIN_SECRET_KEY_LENGTH} characters long '
            'in production; the supplied value does not reach that length.'
        )
    return raw


SECRET_KEY = _resolve_secret_key()

# SECURITY WARNING: never run with debug turned on in production.
DEBUG = env_bool('DEBUG', not IS_PRODUCTION)
if IS_PRODUCTION and DEBUG:
    raise ImproperlyConfigured('DEBUG must be false when APP_ENV=production.')

ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', [] if IS_PRODUCTION else ['localhost', '127.0.0.1', '[::1]'])
if IS_PRODUCTION:
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured(
            'ALLOWED_HOSTS must list the real hostnames when APP_ENV=production.'
        )
    if '*' in ALLOWED_HOSTS:
        raise ImproperlyConfigured(
            'ALLOWED_HOSTS must not contain the wildcard "*" in production: it '
            'disables the Host header check entirely.'
        )

CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS')
if IS_PRODUCTION:
    if not CSRF_TRUSTED_ORIGINS:
        raise ImproperlyConfigured(
            'CSRF_TRUSTED_ORIGINS must list the https:// origins the application '
            'is served from when APP_ENV=production.'
        )
    for _origin in CSRF_TRUSTED_ORIGINS:
        _require_https_url(_origin, 'CSRF_TRUSTED_ORIGINS')


# --------------------------------------------------------------------------
# Security settings
#
# Safe by default in production, adjustable everywhere through the
# environment. HSTS is the deliberate exception: it is never switched on
# implicitly, because a wrong value is remembered by browsers and cannot be
# taken back quickly.
# --------------------------------------------------------------------------

VALID_SAMESITE = ('Lax', 'Strict', 'None')


def _samesite(name, default='Lax'):
    value = os.getenv(name, default).strip() or default
    normalized = value.capitalize() if value.lower() != 'none' else 'None'
    if normalized not in VALID_SAMESITE:
        raise ImproperlyConfigured(
            f'{name} must be one of {", ".join(VALID_SAMESITE)}; got "{value}".'
        )
    return normalized


SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', IS_PRODUCTION)
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', IS_PRODUCTION)
SESSION_COOKIE_HTTPONLY = env_bool('SESSION_COOKIE_HTTPONLY', True)
SESSION_COOKIE_SAMESITE = _samesite('SESSION_COOKIE_SAMESITE')
CSRF_COOKIE_SAMESITE = _samesite('CSRF_COOKIE_SAMESITE')
SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', IS_PRODUCTION)
# Default 0 everywhere on purpose: enable HSTS explicitly, and only once HTTPS
# is known to work for every hostname served.
SECURE_HSTS_SECONDS = env_int('SECURE_HSTS_SECONDS', 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', False)
SECURE_CONTENT_TYPE_NOSNIFF = env_bool('SECURE_CONTENT_TYPE_NOSNIFF', True)
X_FRAME_OPTIONS = os.getenv('X_FRAME_OPTIONS', 'DENY').strip().upper() or 'DENY'
USE_X_FORWARDED_HOST = env_bool('USE_X_FORWARDED_HOST', False)

if IS_PRODUCTION:
    _disabled_security_settings = [
        name
        for name, enabled in (
            ('SESSION_COOKIE_SECURE', SESSION_COOKIE_SECURE),
            ('CSRF_COOKIE_SECURE', CSRF_COOKIE_SECURE),
            ('SECURE_SSL_REDIRECT', SECURE_SSL_REDIRECT),
        )
        if not enabled
    ]
    if _disabled_security_settings:
        raise ImproperlyConfigured(
            f'{", ".join(_disabled_security_settings)} must be true when APP_ENV=production.'
        )

# Trusting `X-Forwarded-Proto` is only safe behind a reverse proxy that
# *overwrites* it. If any client can reach the application directly, a forged
# header would make Django believe an ordinary HTTP request was secure — so
# this is opt-in and off by default.
TRUST_X_FORWARDED_PROTO = env_bool('TRUST_X_FORWARDED_PROTO', False)
if TRUST_X_FORWARDED_PROTO:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# --------------------------------------------------------------------------
# Operational feature flags
# --------------------------------------------------------------------------

# The destructive "delete every act" action exists for local demos only. The
# URL is not even registered unless this is on (see `acts/urls.py`), and
# production can never turn it on: the value is forced off there, and the
# request is additionally reported as a blocking deployment check.
DEMO_RESET_REQUESTED = env_bool('ENABLE_DEMO_RESET', False)
ENABLE_DEMO_RESET = DEMO_RESET_REQUESTED and not IS_PRODUCTION

# An administrative acknowledgement, not evidence: it records that somebody
# takes responsibility for backups. It proves nothing about whether a restore
# has ever been tested.
BACKUP_POLICY_ACKNOWLEDGED = env_bool('BACKUP_POLICY_ACKNOWLEDGED', False)

# Set by the operator when Redis is genuinely on a closed internal network, so
# a plain `redis://` URL is an informed decision rather than an oversight.
REDIS_NETWORK_IS_TRUSTED = env_bool('REDIS_NETWORK_IS_TRUSTED', False)


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# DATABASE_ENGINE selects the backend: "sqlite" (default, no extra
# configuration required) or "postgresql" (requires DB_NAME, DB_USER, and
# DB_PASSWORD; see docs/deployment.md). There is no hidden
# fallback to SQLite if PostgreSQL is selected but misconfigured.

DATABASE_ENGINE = os.getenv('DATABASE_ENGINE', 'sqlite').strip().lower()


def _resolve_sqlite_path():
    """Return the SQLite file to use, honouring the optional SQLITE_DB_PATH.

    Defaults to the existing `BASE_DIR / "db.sqlite3"`. A relative override is
    resolved against BASE_DIR. This exists so a *copy* of the database can be
    exported by the maintenance commands without swapping the working file.
    """
    raw = os.getenv('SQLITE_DB_PATH', '').strip()
    if not raw:
        return BASE_DIR / 'db.sqlite3'
    candidate = Path(raw).expanduser()
    return candidate if candidate.is_absolute() else (BASE_DIR / candidate).resolve()


if IS_PRODUCTION and DATABASE_ENGINE != 'postgresql':
    raise ImproperlyConfigured(
        f'DATABASE_ENGINE must be "postgresql" when APP_ENV=production; got '
        f'"{DATABASE_ENGINE}". SQLite has no concurrent-write story and no '
        'row-level locking, which the act workflow relies on.'
    )

# PostgreSQL runtime parameters. Timeouts are applied per connection through
# the libpq `options` string, so a single runaway query or a forgotten open
# transaction cannot hold a lock indefinitely. `0` disables a timeout, which
# the deployment checks report as a warning rather than silently accepting.
SUPPORTED_SSLMODES = ('disable', 'allow', 'prefer', 'require', 'verify-ca', 'verify-full')
# Modes that still permit an unencrypted connection.
UNENCRYPTED_SSLMODES = ('disable', 'allow', 'prefer')

DB_SSLMODE = os.getenv('DB_SSLMODE', 'prefer').strip().lower() or 'prefer'
if DB_SSLMODE not in SUPPORTED_SSLMODES:
    raise ImproperlyConfigured(
        f'Unsupported DB_SSLMODE "{DB_SSLMODE}". Supported values: '
        f'{", ".join(SUPPORTED_SSLMODES)}.'
    )

DB_APPLICATION_NAME = os.getenv('DB_APPLICATION_NAME', 'quality-ecosystem').strip()
if not DB_APPLICATION_NAME:
    raise ImproperlyConfigured('DB_APPLICATION_NAME must not be empty.')
if len(DB_APPLICATION_NAME) > 63 or not all(
    character.isalnum() or character in '._- ' for character in DB_APPLICATION_NAME
):
    # It is interpolated into the libpq options string and shows up in
    # `pg_stat_activity`, so it stays a short, boring, quote-free identifier.
    raise ImproperlyConfigured(
        'DB_APPLICATION_NAME must be at most 63 characters and contain only '
        'letters, digits, dot, underscore, hyphen or space.'
    )

DB_STATEMENT_TIMEOUT_MS = env_timeout_ms('DB_STATEMENT_TIMEOUT_MS', 30_000)
DB_LOCK_TIMEOUT_MS = env_timeout_ms('DB_LOCK_TIMEOUT_MS', 10_000)
DB_IDLE_IN_TRANSACTION_TIMEOUT_MS = env_timeout_ms('DB_IDLE_IN_TRANSACTION_TIMEOUT_MS', 60_000)


def _postgresql_options():
    """libpq connection options: SSL mode, application name and timeouts."""
    runtime = []
    if DB_STATEMENT_TIMEOUT_MS:
        runtime.append(f'-c statement_timeout={DB_STATEMENT_TIMEOUT_MS}')
    if DB_LOCK_TIMEOUT_MS:
        runtime.append(f'-c lock_timeout={DB_LOCK_TIMEOUT_MS}')
    if DB_IDLE_IN_TRANSACTION_TIMEOUT_MS:
        runtime.append(
            f'-c idle_in_transaction_session_timeout={DB_IDLE_IN_TRANSACTION_TIMEOUT_MS}'
        )
    options = {
        'sslmode': DB_SSLMODE,
        'application_name': DB_APPLICATION_NAME,
    }
    if runtime:
        options['options'] = ' '.join(runtime)
    return options


if DATABASE_ENGINE == 'sqlite':
    SQLITE_DB_PATH = _resolve_sqlite_path()
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': SQLITE_DB_PATH,
            # Deliberately no PostgreSQL OPTIONS here: sslmode, application_name
            # and libpq timeouts are meaningless to SQLite and would raise.
        }
    }
elif DATABASE_ENGINE == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env_str_required('DB_NAME'),
            'USER': env_str_required('DB_USER'),
            'PASSWORD': env_str_required('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': env_int('DB_PORT', 5432),
            # 0 stays the recommended default under ASGI: a long-lived stream
            # must not pin a connection for its whole lifetime. Persistent
            # connections or a pooler are a decision for after a real load
            # test, not a default.
            'CONN_MAX_AGE': env_int('DB_CONN_MAX_AGE', 0),
            'CONN_HEALTH_CHECKS': env_bool('DB_CONN_HEALTH_CHECKS', False),
            'OPTIONS': _postgresql_options(),
        }
    }
else:
    raise ImproperlyConfigured(
        f'Unsupported DATABASE_ENGINE "{DATABASE_ENGINE}". Supported values: sqlite, postgresql.'
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Asia/Yekaterinburg'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
# Where `collectstatic` gathers everything the web server may publish.
# **Public by design** — CSS, JavaScript and images only. It is deliberately a
# different directory from MEDIA_ROOT, which must never be served this way.
STATIC_ROOT = env_path('STATIC_ROOT_PATH', BASE_DIR / 'staticfiles')

# MEDIA_ROOT holds act attachments and is **protected**: files are served only
# through `acts.views.act_download_attachment`, which re-checks permissions for
# every download. It must never be exposed by the web server directly.
MEDIA_URL = 'media/'


def _resolve_media_root():
    """Return the media directory, honouring the optional MEDIA_ROOT_PATH.

    Defaults to the existing `BASE_DIR / "media"`. A relative override is
    resolved against BASE_DIR. This exists so a rehearsal can import a bundle
    into a *separate* target media directory without touching the working one.
    """
    raw = os.getenv('MEDIA_ROOT_PATH', '').strip()
    if not raw:
        return BASE_DIR / 'media'
    candidate = Path(raw).expanduser()
    return candidate if candidate.is_absolute() else (BASE_DIR / candidate).resolve()


MEDIA_ROOT = _resolve_media_root()

LOGIN_URL = 'accounts:login'
# The acts registry is the working page. `accounts.views.AppLoginView` sends an
# administrator to the dashboard instead; this is the fallback everything else
# in Django (including `redirect_to_login`) uses.
LOGIN_REDIRECT_URL = 'acts:list'
LOGOUT_REDIRECT_URL = 'accounts:login'


# Email notifications are deliberately disabled by default. SMTP credentials are
# read only from the deployment environment and must never be committed.
EMAIL_NOTIFICATIONS_ENABLED = env_bool('EMAIL_NOTIFICATIONS_ENABLED', False)
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
APP_BASE_URL = os.getenv('APP_BASE_URL', 'http://127.0.0.1:8000').strip().rstrip('/')
if IS_PRODUCTION:
    # Notification emails carry links built from this; an http:// value would
    # send users to an unencrypted address.
    _require_https_url(APP_BASE_URL, 'APP_BASE_URL')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'quality-ecosystem@localhost')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = env_int('EMAIL_PORT', 25)
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', False)
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', False)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_TIMEOUT = env_int('EMAIL_TIMEOUT', 10)
EMAIL_NOTIFICATION_MAX_ATTEMPTS = env_int('EMAIL_NOTIFICATION_MAX_ATTEMPTS', 3)
EMAIL_NOTIFICATION_RETRY_DELAY_SECONDS = env_int('EMAIL_NOTIFICATION_RETRY_DELAY_SECONDS', 300)
EMAIL_NOTIFICATION_BATCH_SIZE = env_int('EMAIL_NOTIFICATION_BATCH_SIZE', 100)
EMAIL_NOTIFICATION_PROCESSING_TIMEOUT_SECONDS = env_int(
    'EMAIL_NOTIFICATION_PROCESSING_TIMEOUT_SECONDS',
    900,
)


# Real-time events
#
# Disabled by default: with REALTIME_ENABLED=false the emitters return before
# resolving any recipient, so no extra query runs and no Redis client is built.
# The default backend sends nothing; the Redis/SSE transport is selected by
# pointing REALTIME_PUBLISHER_BACKEND at it — business code never changes.
REALTIME_ENABLED = env_bool('REALTIME_ENABLED', False)
REALTIME_PUBLISHER_BACKEND = os.getenv(
    'REALTIME_PUBLISHER_BACKEND',
    'realtime.backends.NoopRealtimePublisher',
)
# A publisher failure happens after the business transaction is committed, so
# by default it is logged and swallowed. Set to false in a test or diagnostic
# environment to let the exception surface.
REALTIME_FAIL_SILENTLY = env_bool('REALTIME_FAIL_SILENTLY', True)

# Redis transport. Nothing here is read while REALTIME_ENABLED=false and the
# Noop publisher is selected: no client is built and no connection is made, so
# `manage.py check` and an ordinary run need no Redis server at all.
REALTIME_REDIS_URL = os.getenv('REALTIME_REDIS_URL', 'redis://127.0.0.1:6379/0')
# Namespace for every Pub/Sub channel: `<prefix>:<target.key>`.
REALTIME_CHANNEL_PREFIX = os.getenv('REALTIME_CHANNEL_PREFIX', 'quality-ecosystem:realtime')
# Deliberately short: publication runs inside `on_commit`, i.e. inside the
# user's own request. An unreachable Redis must cost that request ~1 second,
# not 5 — the event is best-effort and the client resyncs anyway. Real
# deployments can raise these through the environment if the network needs it.
REALTIME_REDIS_CONNECT_TIMEOUT_SECONDS = env_number(
    'REALTIME_REDIS_CONNECT_TIMEOUT_SECONDS', 1.0, minimum=0.1, maximum=60.0
)
REALTIME_REDIS_SOCKET_TIMEOUT_SECONDS = env_number(
    'REALTIME_REDIS_SOCKET_TIMEOUT_SECONDS', 1.0, minimum=0.1, maximum=60.0
)
# A pipelined publish slower than this is logged as `realtime.slow_publish`
# with the event type, channel count and duration only — never the payload,
# the Redis URL or any credential.
REALTIME_REDIS_SLOW_PUBLISH_MS = env_number(
    'REALTIME_REDIS_SLOW_PUBLISH_MS', 250.0, minimum=1.0, maximum=60000.0
)
# Silence between events after which the stream emits an SSE comment, so proxies
# and clients can tell a live connection from a dead one.
REALTIME_HEARTBEAT_SECONDS = env_number(
    'REALTIME_HEARTBEAT_SECONDS', 25.0, minimum=1.0, maximum=300.0
)
# Reconnect delay advertised to the client in the initial `retry:` frame.
REALTIME_RECONNECT_DELAY_MS = env_number(
    'REALTIME_RECONNECT_DELAY_MS', 3000, minimum=100, maximum=300000, cast=int
)
# Hard ceiling for one serialized event, enforced before publishing and again
# before writing to the stream.
REALTIME_MAX_EVENT_BYTES = env_number(
    'REALTIME_MAX_EVENT_BYTES', 16384, minimum=256, maximum=1048576, cast=int
)

# Recovery and multi-tab behaviour. Only these plain numbers reach the browser;
# nothing about Redis ever does.
#
# How long the client may stay without a successful SSE `open` before it
# declares itself degraded and starts polling `/realtime/sync/`.
REALTIME_DEGRADED_AFTER_SECONDS = env_number(
    'REALTIME_DEGRADED_AFTER_SECONDS', 20.0, minimum=5.0, maximum=300.0
)
# Fallback poll interval for a visible tab, and for a hidden one.
REALTIME_SYNC_POLL_SECONDS = env_number(
    'REALTIME_SYNC_POLL_SECONDS', 30.0, minimum=5.0, maximum=600.0
)
REALTIME_SYNC_HIDDEN_POLL_SECONDS = env_number(
    'REALTIME_SYNC_HIDDEN_POLL_SECONDS', 90.0, minimum=10.0, maximum=1800.0
)
# A stream is closed after this long so the client re-authenticates and
# re-checks permissions on a fresh connection. Must exceed the heartbeat.
REALTIME_MAX_CONNECTION_SECONDS = env_number(
    'REALTIME_MAX_CONNECTION_SECONDS', 900.0, minimum=30.0, maximum=86400.0
)
# Leader-tab lease: how long a lease is valid and how often it is renewed.
REALTIME_LEADER_LEASE_SECONDS = env_number(
    'REALTIME_LEADER_LEASE_SECONDS', 12.0, minimum=2.0, maximum=300.0
)
REALTIME_LEADER_HEARTBEAT_SECONDS = env_number(
    'REALTIME_LEADER_HEARTBEAT_SECONDS', 4.0, minimum=1.0, maximum=120.0
)
# How often a live leader tab re-runs `/realtime/sync/` as a safety net
# against a Redis event that was published but never delivered. Deliberately
# rare — this is not a polling replacement, only a periodic correctness check
# while SSE itself is working.
REALTIME_LIVE_SYNC_SECONDS = env_number(
    'REALTIME_LIVE_SYNC_SECONDS', 300.0, minimum=60.0, maximum=1800.0
)


# --------------------------------------------------------------------------
# Logging
#
# **The rotating text file is the primary diagnostic record for the pilot.**
# It is human-readable, stays on the server, and needs no external service to
# read. Console output stays available alongside it so a process manager
# (systemd, a Windows service, a container runtime) can collect the same
# stream, and so a centralised collector can be added later without touching
# any business code. No third-party logging framework is involved.
#
# One line per event:
#     [timestamp] LEVEL logger request=<request_id> user=<user_id>: event key=value ...
#
# **What must never be logged**: SECRET_KEY, DB_PASSWORD, a Redis URL with
# credentials, EMAIL_HOST_PASSWORD, session cookies, CSRF tokens, comment text,
# defect descriptions, KO decision text, root causes, customer and party data,
# recipient email addresses, message subjects and bodies, and the content or
# names of uploaded files. The application logs identifiers, codes, counts,
# durations and outcomes — never payload. `ecosystem.logging_utils.log_event()`
# is the helper for this, `realtime.transport.sanitize()` for Redis specifics,
# and `SensitiveValueRedactionFilter` is the safety net on every handler.
#
# **Rotation is single-process.** `RotatingFileHandler` is safe for the
# one-worker pilot. Several Uvicorn workers rotating one shared file would
# interleave and lose records — with more than one worker, use console output
# plus OS-level collection/rotation instead. See docs/operations.md.
# --------------------------------------------------------------------------

LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO').strip().upper() or 'INFO'
REALTIME_LOG_LEVEL = os.getenv('REALTIME_LOG_LEVEL', LOG_LEVEL).strip().upper() or LOG_LEVEL
# The file is the primary record in production and opt-in elsewhere, so a
# fresh clone still writes nothing to disk without being asked.
LOG_TO_FILE = env_bool('LOG_TO_FILE', IS_PRODUCTION)
# Console stays on everywhere by default: it costs nothing and it is what a
# process manager and any future centralised collector read.
LOG_TO_CONSOLE = env_bool('LOG_TO_CONSOLE', True)
if not LOG_TO_FILE and not LOG_TO_CONSOLE:
    raise ImproperlyConfigured(
        'At least one log handler must be enabled: set LOG_TO_FILE=true or '
        'LOG_TO_CONSOLE=true. Running with no handler would discard every '
        'error message silently.'
    )

# No production path is hardcoded: the deployment supplies an absolute path
# outside the repository. The local fallback keeps a fresh clone working.
LOG_FILE_PATH = env_path('LOG_FILE_PATH', BASE_DIR / 'logs' / 'application.log')
LOG_FILE_MAX_BYTES = env_int('LOG_FILE_MAX_BYTES', 20 * 1024 * 1024)
LOG_FILE_BACKUP_COUNT = env_int('LOG_FILE_BACKUP_COUNT', 10)

# A request slower than this is logged even when it is an ordinary successful
# read, because a slow read is the symptom worth catching early.
LOG_SLOW_REQUEST_MS = env_int('LOG_SLOW_REQUEST_MS', 2000)
# Every POST/PUT/PATCH/DELETE gets one INFO line. Turning this off leaves only
# errors and slow requests, for a deployment that wants a very quiet log.
LOG_MUTATING_REQUESTS = env_bool('LOG_MUTATING_REQUESTS', True)
# Health probes run every few seconds; logging them buries everything else.
# Switch on temporarily when diagnosing a load balancer.
LOG_HEALTH_REQUESTS = env_bool('LOG_HEALTH_REQUESTS', False)

# An optional, safe build marker (a version or short commit SHA) recorded once
# at startup so a log file can be tied to the code that produced it.
APP_RELEASE = os.getenv('APP_RELEASE', '').strip()

_LOG_HANDLERS = ([  # noqa: RUF005 - explicit order: console first, file second
    'console'
] if LOG_TO_CONSOLE else []) + (['file'] if LOG_TO_FILE else [])

if LOG_TO_FILE:
    # Created eagerly so a missing directory is a startup error the operator
    # sees immediately, not a silently dropped log an hour into the pilot.
    LOG_FILE_PATH.parent.mkdir(parents=True, exist_ok=True)

_LOG_FILTERS = ['request_context', 'redact_secrets']

LOGGING = {
    'version': 1,
    # Django's own defaults stay in place.
    'disable_existing_loggers': False,
    'filters': {
        'request_context': {'()': 'ecosystem.logging_utils.RequestContextFilter'},
        # Applied to every handler, so a secret that reaches a record from any
        # source — including Django internals and third-party libraries — is
        # masked before it is written.
        'redact_secrets': {'()': 'ecosystem.logging_utils.SensitiveValueRedactionFilter'},
    },
    'formatters': {
        'safe': {
            # Redaction runs again after formatting, so a stack trace rendered
            # by the formatter cannot smuggle a secret past the filters.
            '()': 'ecosystem.logging_utils.SafeFormatter',
            'format': (
                '[%(asctime)s] %(levelname)s %(name)s '
                'request=%(request_id)s user=%(user_id)s: %(message)s'
            ),
        },
    },
    'handlers': {
        **(
            {
                'console': {
                    'class': 'logging.StreamHandler',
                    'formatter': 'safe',
                    'filters': _LOG_FILTERS,
                }
            }
            if LOG_TO_CONSOLE
            else {}
        ),
        **(
            {
                'file': {
                    'class': 'logging.handlers.RotatingFileHandler',
                    'filename': str(LOG_FILE_PATH),
                    'maxBytes': LOG_FILE_MAX_BYTES,
                    'backupCount': LOG_FILE_BACKUP_COUNT,
                    'encoding': 'utf-8',
                    'formatter': 'safe',
                    'filters': _LOG_FILTERS,
                }
            }
            if LOG_TO_FILE
            else {}
        ),
    },
    'loggers': {
        # Unhandled exceptions and 4xx/5xx responses.
        'django.request': {'handlers': _LOG_HANDLERS, 'level': LOG_LEVEL, 'propagate': False},
        # Host header failures, suspicious operations, CSRF rejections.
        'django.security': {'handlers': _LOG_HANDLERS, 'level': LOG_LEVEL, 'propagate': False},
        # One line per mutating, slow or failed HTTP request.
        'ecosystem.request': {'handlers': _LOG_HANDLERS, 'level': LOG_LEVEL, 'propagate': False},
        # Process startup and the logging self-check.
        'ecosystem.startup': {'handlers': _LOG_HANDLERS, 'level': LOG_LEVEL, 'propagate': False},
        # Act and task workflow transitions: ids, statuses, outcomes only.
        'ecosystem.workflow': {'handlers': _LOG_HANDLERS, 'level': LOG_LEVEL, 'propagate': False},
        # Protected attachment upload, download and refusal.
        'ecosystem.attachments': {'handlers': _LOG_HANDLERS, 'level': LOG_LEVEL, 'propagate': False},
        # Delivery attempts and their outcomes — never the message body.
        'notifications.email': {'handlers': _LOG_HANDLERS, 'level': LOG_LEVEL, 'propagate': False},
        # Migration/transfer tooling.
        'maintenance': {'handlers': _LOG_HANDLERS, 'level': LOG_LEVEL, 'propagate': False},
        # Deployment checks, health probes and readiness reports.
        'deployment': {'handlers': _LOG_HANDLERS, 'level': LOG_LEVEL, 'propagate': False},
        'realtime': {
            'handlers': _LOG_HANDLERS,
            'level': REALTIME_LOG_LEVEL,
            'propagate': False,
        },
    },
}
