# Generated by Django 6.0.6 on 2026-07-23 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_new_task_status(apps, schema_editor):
    TaskStatus = apps.get_model('references', 'TaskStatus')
    TaskStatus.objects.update_or_create(
        code='NEW',
        defaults={
            'name': 'Новая',
            'sort_order': 10,
            'is_final': False,
            'is_active': True,
        },
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('acts', '0015_act_approved_at_act_approved_by_and_more'),
        ('references', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(add_new_task_status, migrations.RunPython.noop),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.TextField(verbose_name='Задача')),
                ('due_date', models.DateField(verbose_name='Срок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='acts.act', verbose_name='Акт')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.department', verbose_name='Подразделение')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('root_analysis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='acts.actrootanalysis', verbose_name='Корневая причина')),
                ('source_action', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='task', to='acts.actcorrectiveaction', verbose_name='Исходное корректирующее мероприятие')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.taskstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['due_date', 'created_at'],
            },
        ),
    ]
