# Generated by Django 6.0.6 on 2026-07-24 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_responsible_to_assignees(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    Assignee = apps.get_model('tasks', 'TaskAssignee')
    Assignee.objects.bulk_create([
        Assignee(task_id=task.pk, user_id=task.responsible_id)
        for task in Task.objects.exclude(responsible_id__isnull=True)
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершена'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Завершил'),
        ),
        migrations.CreateModel(
            name='TaskAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='tasks.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Исполнитель задачи',
                'verbose_name_plural': 'Исполнители задач',
                'constraints': [models.UniqueConstraint(fields=('task', 'user'), name='unique_task_assignee')],
            },
        ),
        migrations.RunPython(copy_responsible_to_assignees, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='task',
            name='responsible',
        ),
    ]
