# Generated by Django 6.0.6 on 2026-07-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_responsible_task_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='execution_comment',
            field=models.TextField(blank=True, verbose_name='Результат выполнения'),
        ),
    ]
