"""Act workflow routing tasks, and optional attachments on ordinary tasks.

Nothing here rewrites a row. `workflow_stage` is added blank — which is exactly
what every existing task means, since none of them is an `ACT_WORKFLOW` entry —
and `department` merely becomes nullable at the column level. The source-shape
check constraint is dropped and re-added rather than edited, as it always is:
it is one constraint listing every valid shape, and it now also states
`department IS NOT NULL` and `workflow_stage = ''` on the three existing
branches, so relaxing the column weakens nothing for `ACT`,
`PROTOCOL_APPROVAL` or `PROTOCOL_ACTION`.

`TaskAttachment` is a new empty table following the act/protocol attachment
pattern: UUID storage paths under `MEDIA_ROOT`, metadata only in the database.
No task is created, deleted or renumbered.
"""

# Generated by Django 6.0.6 on 2026-09-01 10:57

import django.db.models.deletion
import tasks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_mas_department'),
        ('acts', '0025_act_task_split'),
        ('protocols', '0005_protocol_collaboration'),
        ('references', '0003_simplify_task_statuses'),
        ('tasks', '0010_act_task_split'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tasks.models.task_attachment_upload_to, verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер файла')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='Тип содержимого')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
            ],
            options={
                'verbose_name': 'Вложение задачи',
                'verbose_name_plural': 'Вложения задач',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='task_source_relations_match_source_type',
        ),
        migrations.AddField(
            model_name='task',
            name='workflow_stage',
            field=models.CharField(blank=True, choices=[('KO_REVIEW', 'Рассмотрение КО'), ('TO_ANALYSIS', 'Анализ ТО'), ('OTK_REVIEW', 'Итоговая проверка ОТК'), ('OTK_REWORK', 'Доработка ОТК')], max_length=32, verbose_name='Этап маршрута акта'),
        ),
        migrations.AlterField(
            model_name='task',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.department', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='task',
            name='source_type',
            field=models.CharField(choices=[('ACT', 'По акту'), ('PROTOCOL_APPROVAL', 'Согласование протокола'), ('PROTOCOL_ACTION', 'По протоколу'), ('ACT_WORKFLOW', 'Этап обработки акта')], default='ACT', max_length=32, verbose_name='Тип источника'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('act__isnull', False), ('department__isnull', False), ('protocol__isnull', True), ('protocol_action__isnull', True), ('root_analysis__isnull', False), ('source_action__isnull', False), ('source_type', 'ACT'), ('workflow_stage', '')), models.Q(('act__isnull', True), ('department__isnull', False), ('individual_assignee__isnull', True), ('protocol__isnull', False), ('protocol_action__isnull', True), ('root_analysis__isnull', True), ('source_action__isnull', True), ('source_type', 'PROTOCOL_APPROVAL'), ('workflow_stage', '')), models.Q(('act__isnull', True), ('department__isnull', False), ('protocol__isnull', False), ('protocol_action__isnull', False), ('root_analysis__isnull', True), ('source_action__isnull', True), ('source_type', 'PROTOCOL_ACTION'), ('workflow_stage', '')), models.Q(('act__isnull', False), ('individual_assignee__isnull', True), ('protocol__isnull', True), ('protocol_action__isnull', True), ('root_analysis__isnull', True), ('source_action__isnull', True), ('source_type', 'ACT_WORKFLOW'), models.Q(('workflow_stage', ''), _negated=True)), _connector='OR'), name='task_source_relations_match_source_type'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
    ]
