"""`ACT_REJECTION`: the ПДО task a КО «запретить использование» produces.

Schema only — no row is read, written or reclassified. The source-shape check
constraint is dropped and re-added as it always is (it is one constraint
listing every valid shape), gaining an `ACT_REJECTION` branch and changing
nothing about the four that already exist. The new partial unique index makes
«one rejection task per act» a database fact rather than a service check, so a
retried or concurrent КО transition cannot duplicate it; every other source
type fails the index condition and is unaffected.
"""

# Generated by Django 6.0.6 on 2026-09-01 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_mas_department'),
        ('acts', '0025_act_task_split'),
        ('protocols', '0005_protocol_collaboration'),
        ('references', '0003_simplify_task_statuses'),
        ('tasks', '0011_act_workflow_tasks_and_attachments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='task_source_relations_match_source_type',
        ),
        migrations.AlterField(
            model_name='task',
            name='source_type',
            field=models.CharField(choices=[('ACT', 'По акту'), ('PROTOCOL_APPROVAL', 'Согласование протокола'), ('PROTOCOL_ACTION', 'По протоколу'), ('ACT_WORKFLOW', 'Этап обработки акта'), ('ACT_REJECTION', 'Брак по акту')], default='ACT', max_length=32, verbose_name='Тип источника'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('act__isnull', False), ('department__isnull', False), ('protocol__isnull', True), ('protocol_action__isnull', True), ('root_analysis__isnull', False), ('source_action__isnull', False), ('source_type', 'ACT'), ('workflow_stage', '')), models.Q(('act__isnull', True), ('department__isnull', False), ('individual_assignee__isnull', True), ('protocol__isnull', False), ('protocol_action__isnull', True), ('root_analysis__isnull', True), ('source_action__isnull', True), ('source_type', 'PROTOCOL_APPROVAL'), ('workflow_stage', '')), models.Q(('act__isnull', True), ('department__isnull', False), ('protocol__isnull', False), ('protocol_action__isnull', False), ('root_analysis__isnull', True), ('source_action__isnull', True), ('source_type', 'PROTOCOL_ACTION'), ('workflow_stage', '')), models.Q(('act__isnull', False), ('department__isnull', False), ('individual_assignee__isnull', True), ('protocol__isnull', True), ('protocol_action__isnull', True), ('root_analysis__isnull', True), ('source_action__isnull', True), ('source_type', 'ACT_REJECTION'), ('workflow_stage', '')), models.Q(('act__isnull', False), ('individual_assignee__isnull', True), ('protocol__isnull', True), ('protocol_action__isnull', True), ('root_analysis__isnull', True), ('source_action__isnull', True), ('source_type', 'ACT_WORKFLOW'), models.Q(('workflow_stage', ''), _negated=True)), _connector='OR'), name='task_source_relations_match_source_type'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('source_type', 'ACT_REJECTION')), fields=('act',), name='unique_act_rejection_task'),
        ),
    ]
