# Generated by Django 6.0.6 on 2026-09-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_backfill_active_act_deadlines_and_workflow_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='requires_attachment',
            field=models.BooleanField(default=False, verbose_name='Требуется вложение'),
        ),
    ]
