"""`SMK`: the task an Отдел СМК корректирующее мероприятие becomes.

Schema only — no row is read, written or reclassified. The source-shape check
constraint is dropped and re-added as it always is (it is one constraint
listing every valid shape): it gains an `SMK` branch, and every existing branch
gains `smk_source IS NULL` / `smk_action IS NULL`, which no stored row can
violate because both columns are being added NULL in this very migration. The
new partial unique index makes «one task per мероприятие» a database fact; every
other source type has a NULL `smk_action` and is unaffected.
"""

# Generated by Django 6.0.6 on 2026-09-02 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_smk_department'),
        ('acts', '0026_actcorrectiveaction_requires_attachment'),
        ('protocols', '0006_protocolaction_requires_attachment'),
        ('references', '0003_simplify_task_statuses'),
        ('smk', '0001_initial'),
        ('tasks', '0014_task_requires_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='task_source_relations_match_source_type',
        ),
        migrations.AddField(
            model_name='task',
            name='smk_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='smk.smkcorrectiveaction', verbose_name='Корректирующее мероприятие СМК'),
        ),
        migrations.AddField(
            model_name='task',
            name='smk_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='smk.smksource', verbose_name='Запись СМК'),
        ),
        migrations.AlterField(
            model_name='task',
            name='source_type',
            field=models.CharField(choices=[('ACT', 'По акту'), ('PROTOCOL_APPROVAL', 'Согласование протокола'), ('PROTOCOL_ACTION', 'По протоколу'), ('ACT_WORKFLOW', 'Этап обработки акта'), ('ACT_REJECTION', 'Брак по акту'), ('SMK', 'СМК')], default='ACT', max_length=32, verbose_name='Тип источника'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('act__isnull', False), ('department__isnull', False), ('protocol__isnull', True), ('protocol_action__isnull', True), ('root_analysis__isnull', False), ('smk_action__isnull', True), ('smk_source__isnull', True), ('source_action__isnull', False), ('source_type', 'ACT'), ('workflow_stage', '')), models.Q(('act__isnull', True), ('department__isnull', False), ('individual_assignee__isnull', True), ('protocol__isnull', False), ('protocol_action__isnull', True), ('root_analysis__isnull', True), ('smk_action__isnull', True), ('smk_source__isnull', True), ('source_action__isnull', True), ('source_type', 'PROTOCOL_APPROVAL'), ('workflow_stage', '')), models.Q(('act__isnull', True), ('department__isnull', False), ('protocol__isnull', False), ('protocol_action__isnull', False), ('root_analysis__isnull', True), ('smk_action__isnull', True), ('smk_source__isnull', True), ('source_action__isnull', True), ('source_type', 'PROTOCOL_ACTION'), ('workflow_stage', '')), models.Q(('act__isnull', False), ('department__isnull', False), ('individual_assignee__isnull', True), ('protocol__isnull', True), ('protocol_action__isnull', True), ('root_analysis__isnull', True), ('smk_action__isnull', True), ('smk_source__isnull', True), ('source_action__isnull', True), ('source_type', 'ACT_REJECTION'), ('workflow_stage', '')), models.Q(('act__isnull', False), ('individual_assignee__isnull', True), ('protocol__isnull', True), ('protocol_action__isnull', True), ('root_analysis__isnull', True), ('smk_action__isnull', True), ('smk_source__isnull', True), ('source_action__isnull', True), ('source_type', 'ACT_WORKFLOW'), models.Q(('workflow_stage', ''), _negated=True)), models.Q(('act__isnull', True), ('department__isnull', False), ('individual_assignee__isnull', True), ('protocol__isnull', True), ('protocol_action__isnull', True), ('root_analysis__isnull', True), ('smk_action__isnull', False), ('smk_source__isnull', False), ('source_action__isnull', True), ('source_type', 'SMK'), ('workflow_stage', '')), _connector='OR'), name='task_source_relations_match_source_type'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('smk_action',), name='unique_smk_action_task'),
        ),
    ]
