# Generated by Django 6.0.6 on 2026-09-03 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_smk_task_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='task',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отменена'),
        ),
        migrations.AddField(
            model_name='task',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Отменил'),
        ),
    ]
