# Generated by Django 6.0.6 on 2026-09-04 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_is_bug_responsible'),
        ('acts', '0026_actcorrectiveaction_requires_attachment'),
        ('bugs', '0001_initial'),
        ('protocols', '0007_web_system_protocol_type'),
        ('references', '0004_cancelled_task_status'),
        ('smk', '0009_smk_source_archived_label'),
        ('tasks', '0017_smk_task_split'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='task_source_relations_match_source_type',
        ),
        migrations.AddField(
            model_name='task',
            name='bug_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='bugs.bugreport', verbose_name='Сообщение об ошибке'),
        ),
        migrations.AlterField(
            model_name='task',
            name='source_type',
            field=models.CharField(choices=[('ACT', 'По акту'), ('PROTOCOL_APPROVAL', 'Согласование протокола'), ('PROTOCOL_ACTION', 'По протоколу'), ('ACT_WORKFLOW', 'Этап обработки акта'), ('ACT_REJECTION', 'Брак по акту'), ('SMK', 'СМК'), ('BUG', 'Ошибка в системе')], default='ACT', max_length=32, verbose_name='Тип источника'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('act__isnull', False), ('bug_report__isnull', True), ('department__isnull', False), ('protocol__isnull', True), ('protocol_action__isnull', True), ('root_analysis__isnull', False), ('smk_action__isnull', True), ('smk_source__isnull', True), ('source_action__isnull', False), ('source_type', 'ACT'), ('workflow_stage', '')), models.Q(('act__isnull', True), ('bug_report__isnull', True), ('department__isnull', False), ('individual_assignee__isnull', True), ('protocol__isnull', False), ('protocol_action__isnull', True), ('root_analysis__isnull', True), ('smk_action__isnull', True), ('smk_source__isnull', True), ('source_action__isnull', True), ('source_type', 'PROTOCOL_APPROVAL'), ('workflow_stage', '')), models.Q(('act__isnull', True), ('bug_report__isnull', True), ('department__isnull', False), ('protocol__isnull', False), ('protocol_action__isnull', False), ('root_analysis__isnull', True), ('smk_action__isnull', True), ('smk_source__isnull', True), ('source_action__isnull', True), ('source_type', 'PROTOCOL_ACTION'), ('workflow_stage', '')), models.Q(('act__isnull', False), ('bug_report__isnull', True), ('department__isnull', False), ('individual_assignee__isnull', True), ('protocol__isnull', True), ('protocol_action__isnull', True), ('root_analysis__isnull', True), ('smk_action__isnull', True), ('smk_source__isnull', True), ('source_action__isnull', True), ('source_type', 'ACT_REJECTION'), ('workflow_stage', '')), models.Q(('act__isnull', False), ('bug_report__isnull', True), ('individual_assignee__isnull', True), ('protocol__isnull', True), ('protocol_action__isnull', True), ('root_analysis__isnull', True), ('smk_action__isnull', True), ('smk_source__isnull', True), ('source_action__isnull', True), ('source_type', 'ACT_WORKFLOW'), models.Q(('workflow_stage', ''), _negated=True)), models.Q(('act__isnull', True), ('bug_report__isnull', True), ('department__isnull', False), ('protocol__isnull', True), ('protocol_action__isnull', True), ('root_analysis__isnull', True), ('smk_action__isnull', False), ('smk_source__isnull', False), ('source_action__isnull', True), ('source_type', 'SMK'), ('workflow_stage', '')), models.Q(('act__isnull', True), ('bug_report__isnull', False), ('department__isnull', True), ('individual_assignee__isnull', True), ('protocol__isnull', True), ('protocol_action__isnull', True), ('root_analysis__isnull', True), ('smk_action__isnull', True), ('smk_source__isnull', True), ('source_action__isnull', True), ('source_type', 'BUG'), ('workflow_stage', '')), _connector='OR'), name='task_source_relations_match_source_type'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('bug_report',), name='unique_bug_report_task'),
        ),
    ]
