# Generated by Django 6.0.6 on 2026-08-14 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WindingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Магнитопровод')),
                ('case_key', models.CharField(max_length=120, unique=True, verbose_name='Ключ расчётного случая')),
                ('d', models.FloatField(verbose_name='d, мм')),
                ('outer_diameter', models.FloatField(verbose_name='D, мм')),
                ('b', models.FloatField(verbose_name='b, мм')),
                ('tape_thickness_mm', models.FloatField(verbose_name='Толщина ленты, мм')),
                ('height_mm', models.FloatField(verbose_name='Высота навивки, мм')),
                ('calibration_enabled', models.BooleanField(default=False, verbose_name='Калибровка')),
                ('calibration_diameter_mm', models.FloatField(blank=True, null=True, verbose_name='Радиус калибровки, мм')),
                ('standard_coefficient', models.FloatField(verbose_name='Скорость навивки, сек/мм')),
                ('raw_complexity_coefficient', models.FloatField(verbose_name='КС без округления')),
                ('complexity_coefficient', models.FloatField(verbose_name='КС')),
                ('winding_time_seconds', models.FloatField(verbose_name='Время навивки, с')),
                ('additional_operations_time_seconds', models.FloatField(verbose_name='Время доп. операций, с')),
                ('total_time_seconds', models.FloatField(verbose_name='Расчётное время, с')),
                ('batch_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Единиц в партии')),
                ('actual_batch_time_hours', models.FloatField(blank=True, null=True, verbose_name='Фактическое время партии, ч')),
                ('actual_unit_time_hours', models.FloatField(blank=True, null=True, verbose_name='Фактическое время единицы, ч')),
                ('production_confirmed', models.BooleanField(default=False, verbose_name='Производственные данные подтверждены')),
                ('calculation_version', models.PositiveSmallIntegerField(default=1, verbose_name='Версия расчёта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_winding_entries', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_winding_entries', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Расчёт навивки',
                'verbose_name_plural': 'Расчёты навивки',
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
