# Generated by Django 6.0.8 on 2026-10-05 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="В архиве с"
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Убрал в архив",
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Активна"), ("ARCHIVED", "В архиве")],
                default="ACTIVE",
                max_length=16,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="boardcard",
            name="version",
            field=models.PositiveIntegerField(default=1, verbose_name="Версия"),
        ),
    ]
