# Generated by Django 6.0.8 on 2026-10-05 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0002_board_archive_card_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardCardComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="board_card_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comments",
                        to="boards.boardcard",
                        verbose_name="Карточка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение в карточке",
                "verbose_name_plural": "Сообщения в карточках",
                "ordering": ["created_at", "pk"],
                "indexes": [
                    models.Index(
                        fields=["card", "created_at"], name="board_card_comment_time"
                    )
                ],
            },
        ),
    ]
