# Generated by Django 6.0.8 on 2026-10-06 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_userprofile_is_document_responsible"),
        ("boards", "0003_board_card_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="boards",
                to="accounts.department",
                verbose_name="Подразделение",
            ),
        ),
    ]
