# Generated by Django 6.0.8 on 2026-10-06 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0004_board_department_optional"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="Название")),
                ("position", models.PositiveIntegerField(verbose_name="Позиция")),
                (
                    "is_done",
                    models.BooleanField(default=False, verbose_name="Завершающая"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
            ],
            options={
                "verbose_name": "Колонка доски",
                "verbose_name_plural": "Колонки досок",
                "ordering": ["sub_board_id", "position", "pk"],
            },
        ),
        migrations.AddField(
            model_name="boardcard",
            name="column",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cards",
                to="boards.boardcolumn",
                verbose_name="Колонка",
            ),
        ),
        migrations.CreateModel(
            name="SubBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("position", models.PositiveIntegerField(verbose_name="Позиция")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sub_boards",
                        to="boards.board",
                        verbose_name="Доска",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поддоска",
                "verbose_name_plural": "Поддоски",
                "ordering": ["board_id", "position", "pk"],
            },
        ),
        migrations.AddField(
            model_name="boardcolumn",
            name="sub_board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="columns",
                to="boards.subboard",
                verbose_name="Поддоска",
            ),
        ),
        migrations.AddField(
            model_name="boardcard",
            name="sub_board",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cards",
                to="boards.subboard",
                verbose_name="Поддоска",
            ),
        ),
        migrations.AddConstraint(
            model_name="subboard",
            constraint=models.UniqueConstraint(
                fields=("board", "name"), name="unique_sub_board_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="boardcolumn",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_done", True)),
                fields=("sub_board",),
                name="unique_done_column_per_sub_board",
            ),
        ),
    ]
