# Generated by Django 6.0.8 on 2026-10-06 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0008_drop_card_stage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardCardEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CREATED", "Создание"),
                            ("EDITED", "Изменение"),
                            ("MOVED", "Перенос"),
                            ("COMPLETED", "Завершение"),
                            ("REOPENED", "Возврат в работу"),
                            ("CANCELLED", "Отмена"),
                        ],
                        max_length=20,
                        verbose_name="Событие",
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Подробности"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Когда"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="board_card_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто",
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="boards.boardcard",
                        verbose_name="Карточка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие карточки",
                "verbose_name_plural": "Журнал карточек",
                "ordering": ["created_at", "pk"],
                "indexes": [
                    models.Index(
                        fields=["card", "created_at"], name="board_card_event_time"
                    )
                ],
            },
        ),
    ]
