# Generated by Django 6.0.8 on 2026-10-07 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0020_due_changes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardCardLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("BLOCKS", "Блокирует"),
                            ("RELATES", "Связана"),
                            ("DUPLICATES", "Дубль"),
                        ],
                        max_length=12,
                        verbose_name="Вид",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
            ],
            options={
                "verbose_name": "Связь карточек",
                "verbose_name_plural": "Связи карточек",
                "ordering": ["created_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="BoardColumnSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Подписан"),
                ),
            ],
            options={
                "verbose_name": "Подписка на колонку",
                "verbose_name_plural": "Подписки на колонки",
                "ordering": ["column_id", "created_at", "pk"],
            },
        ),
        migrations.AddField(
            model_name="boardfield",
            name="sum_in_column",
            field=models.BooleanField(default=False, verbose_name="Сумма в колонке"),
        ),
        migrations.AlterField(
            model_name="boardcardevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("CREATED", "Создание"),
                    ("EDITED", "Изменение"),
                    ("MOVED", "Перенос"),
                    ("COMPLETED", "Завершение"),
                    ("REOPENED", "Возврат в работу"),
                    ("CANCELLED", "Отмена"),
                    ("CHECKLIST", "Чек-лист"),
                    ("SUBTASK", "Подзадача"),
                    ("LINKED", "Связь добавлена"),
                    ("UNLINKED", "Связь удалена"),
                ],
                max_length=20,
                verbose_name="Событие",
            ),
        ),
        migrations.AddConstraint(
            model_name="boardfield",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sum_in_column", False), ("kind", "NUMBER"), _connector="OR"
                ),
                name="board_field_sum_only_number",
            ),
        ),
        migrations.AddField(
            model_name="boardcardlink",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Связал",
            ),
        ),
        migrations.AddField(
            model_name="boardcardlink",
            name="from_card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outgoing_links",
                to="boards.boardcard",
                verbose_name="От карточки",
            ),
        ),
        migrations.AddField(
            model_name="boardcardlink",
            name="to_card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_links",
                to="boards.boardcard",
                verbose_name="К карточке",
            ),
        ),
        migrations.AddField(
            model_name="boardcolumnsubscription",
            name="column",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="boards.boardcolumn",
                verbose_name="Колонка",
            ),
        ),
        migrations.AddField(
            model_name="boardcolumnsubscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="board_column_subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписчик",
            ),
        ),
        migrations.AddIndex(
            model_name="boardcardlink",
            index=models.Index(fields=["to_card", "kind"], name="board_card_link_to"),
        ),
        migrations.AddConstraint(
            model_name="boardcardlink",
            constraint=models.CheckConstraint(
                condition=models.Q(("from_card", models.F("to_card")), _negated=True),
                name="board_card_link_not_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="boardcardlink",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["BLOCKS", "RELATES", "DUPLICATES"])),
                name="board_card_link_kind_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="boardcardlink",
            constraint=models.UniqueConstraint(
                fields=("from_card", "to_card", "kind"), name="unique_board_card_link"
            ),
        ),
        migrations.AddConstraint(
            model_name="boardcolumnsubscription",
            constraint=models.UniqueConstraint(
                fields=("column", "user"), name="unique_board_column_subscription"
            ),
        ),
    ]
