# Generated by Django 6.0.8 on 2026-10-07 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0022_column_norm_working_days"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardDigestSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[("DAILY", "Ежедневно"), ("WEEKLY", "Еженедельно")],
                        max_length=8,
                        verbose_name="Как часто",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Подписан"),
                ),
                (
                    "last_sent_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="Обработан за дату"
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="digest_subscriptions",
                        to="boards.board",
                        verbose_name="Доска",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="board_digest_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка на дайджест доски",
                "verbose_name_plural": "Подписки на дайджест досок",
                "ordering": ["board_id", "user_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("board", "user"),
                        name="unique_board_digest_subscription",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("frequency__in", ["DAILY", "WEEKLY"])),
                        name="board_digest_frequency_known",
                    ),
                ],
            },
        ),
    ]
