# Generated by Django 6.0.8 on 2026-10-07 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_userprofile_is_document_responsible"),
        ("boards", "0023_board_digest_subscriptions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardIntakeHandler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Назначен"),
                ),
            ],
            options={
                "verbose_name": "Разбирающий заявки доски",
                "verbose_name_plural": "Разбирающие заявки досок",
                "ordering": ["board_id", "user_id"],
            },
        ),
        migrations.CreateModel(
            name="BoardRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "desired_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Желаемая дата"
                    ),
                ),
                (
                    "field_values",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Поля доски"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Новая"),
                            ("ACCEPTED", "Принята"),
                            ("REJECTED", "Отклонена"),
                            ("DUPLICATE", "Дубль"),
                            ("WITHDRAWN", "Отозвана"),
                        ],
                        default="NEW",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "decision_comment",
                    models.TextField(blank=True, verbose_name="Комментарий к решению"),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Решение принято"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Подана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
            ],
            options={
                "verbose_name": "Заявка на доску",
                "verbose_name_plural": "Заявки на доски",
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.AddField(
            model_name="board",
            name="intake_column",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="boards.boardcolumn",
                verbose_name="Колонка для заявок",
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="intake_due_days",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Срок по заявке, рабочих дней"
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="intake_enabled",
            field=models.BooleanField(default=False, verbose_name="Приём заявок"),
        ),
        migrations.AddField(
            model_name="board",
            name="intake_hint",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Подсказка над формой заявки"
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="intake_sub_board",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="boards.subboard",
                verbose_name="Поддоска для заявок",
            ),
        ),
        migrations.AddField(
            model_name="boardfield",
            name="in_request_form",
            field=models.BooleanField(default=False, verbose_name="В форме заявки"),
        ),
        migrations.AddField(
            model_name="boardfield",
            name="required_in_request",
            field=models.BooleanField(
                default=False, verbose_name="Обязательно в заявке"
            ),
        ),
        migrations.AddConstraint(
            model_name="board",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("intake_due_days__isnull", True),
                    ("intake_due_days__lte", 365),
                    _connector="OR",
                ),
                name="board_intake_due_days_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="boardfield",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("required_in_request", False),
                    ("in_request_form", True),
                    _connector="OR",
                ),
                name="board_field_required_in_form",
            ),
        ),
        migrations.AddField(
            model_name="boardintakehandler",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intake_handlers",
                to="boards.board",
                verbose_name="Доска",
            ),
        ),
        migrations.AddField(
            model_name="boardintakehandler",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="board_intake_roles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Разбирающий",
            ),
        ),
        migrations.AddField(
            model_name="boardrequest",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="board_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="boardrequest",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requests",
                to="boards.board",
                verbose_name="Доска",
            ),
        ),
        migrations.AddField(
            model_name="boardrequest",
            name="card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requests",
                to="boards.boardcard",
                verbose_name="Карточка",
            ),
        ),
        migrations.AddField(
            model_name="boardrequest",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Решение принял",
            ),
        ),
        migrations.AddField(
            model_name="boardrequest",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="duplicate_requests",
                to="boards.boardcard",
                verbose_name="Дубль карточки",
            ),
        ),
        migrations.AddConstraint(
            model_name="boardintakehandler",
            constraint=models.UniqueConstraint(
                fields=("board", "user"), name="unique_board_intake_handler"
            ),
        ),
        migrations.AddIndex(
            model_name="boardrequest",
            index=models.Index(
                fields=["board", "status", "created_at"], name="board_request_inbox"
            ),
        ),
        migrations.AddIndex(
            model_name="boardrequest",
            index=models.Index(
                fields=["author", "created_at"], name="board_request_author"
            ),
        ),
        migrations.AddConstraint(
            model_name="boardrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["NEW", "ACCEPTED", "REJECTED", "DUPLICATE", "WITHDRAWN"],
                    )
                ),
                name="board_request_status_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="boardrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("card__isnull", False), ("status", "ACCEPTED")),
                    models.Q(
                        models.Q(("status", "ACCEPTED"), _negated=True),
                        ("card__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="board_request_card_only_when_accepted",
            ),
        ),
        migrations.AddConstraint(
            model_name="boardrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("duplicate_of__isnull", False), ("status", "DUPLICATE")),
                    models.Q(
                        models.Q(("status", "DUPLICATE"), _negated=True),
                        ("duplicate_of__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="board_request_duplicate_only_when_duplicate",
            ),
        ),
        migrations.AddConstraint(
            model_name="boardrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("decided_at__isnull", True),
                        ("decided_by__isnull", True),
                        ("decision_comment", ""),
                        ("status", "NEW"),
                    ),
                    models.Q(
                        models.Q(("status", "NEW"), _negated=True),
                        ("decided_at__isnull", False),
                        ("decided_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="board_request_decision_matches_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="boardrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "REJECTED"), _negated=True),
                    models.Q(("decision_comment", ""), _negated=True),
                    _connector="OR",
                ),
                name="board_request_rejection_has_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="boardrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("card__isnull", False)),
                fields=("card",),
                name="unique_board_request_card",
            ),
        ),
    ]
