# Generated by Django 6.0.8 on 2026-10-07 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0024_intake_and_requests"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="boardcard",
            name="is_pinned",
            field=models.BooleanField(default=False, verbose_name="Закреплена"),
        ),
        migrations.CreateModel(
            name="BoardAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="Название")),
                ("position", models.PositiveIntegerField(verbose_name="Позиция")),
                (
                    "assignee_mode",
                    models.CharField(
                        choices=[
                            ("KEEP", "Не менять"),
                            ("ADD", "Добавить к исполнителям"),
                            ("REPLACE", "Заменить исполнителей"),
                        ],
                        default="KEEP",
                        max_length=8,
                        verbose_name="Исполнители",
                    ),
                ),
                (
                    "comment_required",
                    models.BooleanField(
                        default=False, verbose_name="Комментарий обязателен"
                    ),
                ),
                (
                    "message_template",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Сообщение в чат"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="В архиве"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="boards.board",
                        verbose_name="Доска",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_board_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "target_column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="boards.boardcolumn",
                        verbose_name="Колонка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Действие доски",
                "verbose_name_plural": "Действия досок",
                "ordering": ["board_id", "position", "pk"],
            },
        ),
        migrations.CreateModel(
            name="BoardActionAssignee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignee_rows",
                        to="boards.boardaction",
                        verbose_name="Действие",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="board_action_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Исполнитель действия доски",
                "verbose_name_plural": "Исполнители действий досок",
                "ordering": ["action_id", "pk"],
            },
        ),
        migrations.AddField(
            model_name="boardaction",
            name="assignees",
            field=models.ManyToManyField(
                blank=True,
                related_name="board_actions",
                through="boards.BoardActionAssignee",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Новые исполнители",
            ),
        ),
        migrations.CreateModel(
            name="BoardActionFieldRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=500, verbose_name="Значение")),
                (
                    "overwrite",
                    models.BooleanField(default=False, verbose_name="Перезаписывать"),
                ),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_rules",
                        to="boards.boardaction",
                        verbose_name="Действие",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="boards.boardfield",
                        verbose_name="Поле",
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение поля по действию",
                "verbose_name_plural": "Значения полей по действиям",
                "ordering": ["action_id", "pk"],
            },
        ),
        migrations.CreateModel(
            name="BoardColumnChecklistTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="Текст")),
                ("position", models.PositiveIntegerField(verbose_name="Позиция")),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_template",
                        to="boards.boardcolumn",
                        verbose_name="Колонка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт шаблона чек-листа колонки",
                "verbose_name_plural": "Шаблоны чек-листов колонок",
                "ordering": ["column_id", "position", "pk"],
            },
        ),
        migrations.CreateModel(
            name="BoardColumnFieldRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=500, verbose_name="Значение")),
                (
                    "overwrite",
                    models.BooleanField(default=False, verbose_name="Перезаписывать"),
                ),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_rules",
                        to="boards.boardcolumn",
                        verbose_name="Колонка",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="boards.boardfield",
                        verbose_name="Поле",
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение поля по колонке",
                "verbose_name_plural": "Значения полей по колонкам",
                "ordering": ["column_id", "pk"],
            },
        ),
        migrations.CreateModel(
            name="BoardColumnFollower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_followers",
                        to="boards.boardcolumn",
                        verbose_name="Колонка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="board_column_follows",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Подписчик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписчик карточек колонки",
                "verbose_name_plural": "Подписчики карточек колонок",
                "ordering": ["column_id", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="boardactionassignee",
            constraint=models.UniqueConstraint(
                fields=("action", "user"), name="unique_board_action_assignee"
            ),
        ),
        migrations.AddConstraint(
            model_name="boardaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("assignee_mode__in", ["KEEP", "ADD", "REPLACE"])),
                name="board_action_assignee_mode_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="boardactionfieldrule",
            constraint=models.UniqueConstraint(
                fields=("action", "field"), name="unique_board_action_field_rule"
            ),
        ),
        migrations.AddConstraint(
            model_name="boardcolumnfieldrule",
            constraint=models.UniqueConstraint(
                fields=("column", "field"), name="unique_board_column_field_rule"
            ),
        ),
        migrations.AddConstraint(
            model_name="boardcolumnfollower",
            constraint=models.UniqueConstraint(
                fields=("column", "user"), name="unique_board_column_follower"
            ),
        ),
    ]
