# Generated by Django 6.0.6 on 2026-08-01 16:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acts', '0018_alter_act_ko_decision_alter_actdefect_ko_decision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ACT_SENT_TO_KO', 'Акт передан в КО'), ('ACT_SENT_TO_TO', 'Акт передан в ТО'), ('ACT_SENT_TO_OTK', 'Акт передан на проверку ОТК'), ('ACT_RETURNED_TO_OTK', 'Акт возвращён в ОТК'), ('ACT_RETURNED_TO_KO', 'Акт возвращён в КО'), ('ACT_RETURNED_TO_TO', 'Акт возвращён в ТО'), ('ACTION_ASSIGNED', 'Назначено мероприятие'), ('ACT_APPROVED', 'Акт утверждён'), ('COMMENT_ADDED', 'Добавлен комментарий')], max_length=40, verbose_name='Тип события')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('deduplication_key', models.CharField(max_length=180, verbose_name='Ключ дедупликации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано в')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('related_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='acts.act', verbose_name='Связанный акт')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email')], max_length=20, verbose_name='Канал')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('processing', 'Отправляется'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], default='pending', max_length=20, verbose_name='Статус')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Попытки')),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Доступно для отправки')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало обработки')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя попытка')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено в')),
                ('last_error', models.CharField(blank=True, max_length=500, verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification', verbose_name='Уведомление')),
            ],
            options={
                'verbose_name': 'Доставка уведомления',
                'verbose_name_plural': 'Доставки уведомлений',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='notif_rec_read_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['related_act', '-created_at'], name='notif_act_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('recipient', 'deduplication_key'), name='unique_notification_recipient_event'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_read', False), ('read_at__isnull', True)), models.Q(('is_read', True), ('read_at__isnull', False)), _connector='OR'), name='notification_read_state_consistent'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['channel', 'status', 'available_at'], name='delivery_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('notification', 'channel'), name='unique_notification_delivery_channel'),
        ),
    ]
