# Generated by Django 6.0.6 on 2026-09-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_source_shape_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('ACT_SENT_TO_KO', 'Акт передан в КО'), ('ACT_SENT_TO_TO', 'Акт передан в ТО'), ('ACT_SENT_TO_OTK', 'Акт передан на проверку ОТК'), ('ACT_RETURNED_TO_OTK', 'Акт возвращён в ОТК'), ('ACT_RETURNED_TO_KO', 'Акт возвращён в КО'), ('ACT_RETURNED_TO_TO', 'Акт возвращён в ТО'), ('ACTION_ASSIGNED', 'Назначено мероприятие'), ('ACT_APPROVED', 'Акт утверждён'), ('COMMENT_ADDED', 'Добавлен комментарий'), ('PROTOCOL_APPROVAL_REQUIRED', 'Требуется согласование протокола'), ('PROTOCOL_RETURNED_FOR_REVISION', 'Протокол возвращён на доработку'), ('PROTOCOL_APPROVED', 'Протокол согласован'), ('PROTOCOL_TASK_ASSIGNED', 'Назначена задача по протоколу'), ('ACT_REJECTION_ASSIGNED', 'Назначена задача ПДО по браку')], max_length=40, verbose_name='Тип события'),
        ),
    ]
