# Generated by Django 6.0.8 on 2026-09-25 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acts", "0030_open_ko_round_for_acts_in_review"),
        ("bugs", "0001_initial"),
        ("documents", "0008_document_control"),
        ("notifications", "0008_bug_report_source"),
        ("protocols", "0007_web_system_protocol_type"),
        ("tasks", "0018_bug_report_task"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notification",
            name="notification_source_relations_match_source_type",
        ),
        migrations.AddField(
            model_name="notification",
            name="related_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="documents.document",
                verbose_name="Связанный документ",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("ACT_SENT_TO_KO", "Акт передан в КО"),
                    ("ACT_SENT_TO_TO", "Акт передан в ТО"),
                    ("ACT_SENT_TO_OTK", "Акт передан на проверку ОТК"),
                    ("ACT_RETURNED_TO_OTK", "Акт возвращён в ОТК"),
                    ("ACT_RETURNED_TO_KO", "Акт возвращён в КО"),
                    ("ACT_RETURNED_TO_TO", "Акт возвращён в ТО"),
                    ("ACTION_ASSIGNED", "Назначено мероприятие"),
                    ("ACT_APPROVED", "Акт утверждён"),
                    ("COMMENT_ADDED", "Добавлен комментарий"),
                    ("PROTOCOL_APPROVAL_REQUIRED", "Требуется согласование протокола"),
                    (
                        "PROTOCOL_RETURNED_FOR_REVISION",
                        "Протокол возвращён на доработку",
                    ),
                    ("PROTOCOL_APPROVED", "Протокол согласован"),
                    ("PROTOCOL_TASK_ASSIGNED", "Назначена задача по протоколу"),
                    ("ACT_REJECTION_ASSIGNED", "Назначена задача ПДО по браку"),
                    ("SMK_TASK_ASSIGNED", "Назначена задача СМК"),
                    ("BUG_REPORTED", "Сообщение об ошибке в системе"),
                    ("DOCUMENT_ACK_REQUIRED", "Требуется ознакомление с документом"),
                    ("DOCUMENT_APPROVAL_REQUIRED", "Требуется согласование документа"),
                    ("DOCUMENT_REVIEW_DUE", "Подходит срок пересмотра документа"),
                    ("DOCUMENT_VERSION_RETURNED", "Версия документа возвращена"),
                    ("DOCUMENT_UPDATED", "Новая версия документа"),
                ],
                max_length=40,
                verbose_name="Тип события",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("ACT", "Акт"),
                    ("PROTOCOL", "Протокол"),
                    ("TASK", "Задача"),
                    ("BUG", "Сообщение об ошибке"),
                    ("DOCUMENT", "Документ"),
                ],
                default="ACT",
                max_length=16,
                verbose_name="Тип источника",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("related_act__isnull", False),
                        ("related_bug_report__isnull", True),
                        ("related_document__isnull", True),
                        ("related_protocol__isnull", True),
                        ("related_task__isnull", True),
                        ("source_type", "ACT"),
                    ),
                    models.Q(
                        ("related_act__isnull", True),
                        ("related_bug_report__isnull", True),
                        ("related_document__isnull", True),
                        ("related_protocol__isnull", False),
                        ("related_task__isnull", True),
                        ("source_type", "PROTOCOL"),
                    ),
                    models.Q(
                        ("related_act__isnull", True),
                        ("related_bug_report__isnull", True),
                        ("related_document__isnull", True),
                        ("related_protocol__isnull", True),
                        ("related_task__isnull", False),
                        ("source_type", "TASK"),
                    ),
                    models.Q(
                        ("related_act__isnull", True),
                        ("related_bug_report__isnull", False),
                        ("related_document__isnull", True),
                        ("related_protocol__isnull", True),
                        ("related_task__isnull", True),
                        ("source_type", "BUG"),
                    ),
                    models.Q(
                        ("related_act__isnull", True),
                        ("related_bug_report__isnull", True),
                        ("related_document__isnull", False),
                        ("related_protocol__isnull", True),
                        ("related_task__isnull", True),
                        ("source_type", "DOCUMENT"),
                    ),
                    _connector="OR",
                ),
                name="notification_source_relations_match_source_type",
            ),
        ),
    ]
