"""`REQUEST` — a notification about a board request («Заявка №N»),
`boards.BoardRequest`, in place: the nullable `related_board_request`, the
new source type and event types. No row is classified — every existing
notification already has its source — and the source-shape constraint is
swapped for the one with the `REQUEST` branch in `0017`, a migration of
its own."""

# Generated by Django 6.0.8 on 2026-10-07 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acts", "0030_open_ko_round_for_acts_in_review"),
        ("boards", "0024_intake_and_requests"),
        ("bugs", "0001_initial"),
        ("documents", "0008_document_control"),
        ("notifications", "0015_board_unblocked_column_entered"),
        ("protocols", "0007_web_system_protocol_type"),
        ("tasks", "0021_board_task_department_free"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="related_board_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="boards.boardrequest",
                verbose_name="Связанная заявка",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("ACT_SENT_TO_KO", "Акт передан в КО"),
                    ("ACT_SENT_TO_TO", "Акт передан в ТО"),
                    ("ACT_SENT_TO_OTK", "Акт передан на проверку ОТК"),
                    ("ACT_RETURNED_TO_OTK", "Акт возвращён в ОТК"),
                    ("ACT_RETURNED_TO_KO", "Акт возвращён в КО"),
                    ("ACT_RETURNED_TO_TO", "Акт возвращён в ТО"),
                    ("ACTION_ASSIGNED", "Назначено мероприятие"),
                    ("ACT_APPROVED", "Акт утверждён"),
                    ("COMMENT_ADDED", "Добавлен комментарий"),
                    ("PROTOCOL_APPROVAL_REQUIRED", "Требуется согласование протокола"),
                    (
                        "PROTOCOL_RETURNED_FOR_REVISION",
                        "Протокол возвращён на доработку",
                    ),
                    ("PROTOCOL_APPROVED", "Протокол согласован"),
                    ("PROTOCOL_TASK_ASSIGNED", "Назначена задача по протоколу"),
                    ("ACT_REJECTION_ASSIGNED", "Назначена задача ПДО по браку"),
                    ("SMK_TASK_ASSIGNED", "Назначена задача СМК"),
                    ("BOARD_TASK_ASSIGNED", "Назначена задача на доске"),
                    ("BOARD_TASK_CANCELLED", "Карточка отменена"),
                    ("BOARD_CARD_COMMENT", "Новое сообщение в карточке"),
                    ("BOARD_CARD_MENTION", "Упоминание в карточке"),
                    ("BOARD_CARD_COMPLETED", "Карточка выполнена"),
                    ("BOARD_SUBTASKS_DONE", "Все подзадачи выполнены"),
                    ("BOARD_DUE_CHANGED", "Срок карточки перенесён"),
                    ("BOARD_DUE_SOON", "Подходит срок карточки"),
                    ("BOARD_OVERDUE", "Карточка просрочена"),
                    ("BOARD_UNBLOCKED", "Карточку можно начинать"),
                    ("BOARD_COLUMN_ENTERED", "Карточка вошла в колонку"),
                    ("BOARD_REQUEST_NEW", "Новая заявка на доске"),
                    ("BOARD_REQUEST_ACCEPTED", "Заявка принята"),
                    ("BOARD_REQUEST_REJECTED", "Заявка отклонена"),
                    ("BOARD_REQUEST_DUPLICATE", "Заявка отмечена дублем"),
                    ("BOARD_REQUEST_DONE", "Заявка выполнена"),
                    ("BUG_REPORTED", "Сообщение об ошибке в системе"),
                    ("DOCUMENT_ACK_REQUIRED", "Требуется ознакомление с документом"),
                    ("DOCUMENT_APPROVAL_REQUIRED", "Требуется согласование документа"),
                    ("DOCUMENT_REVIEW_DUE", "Подходит срок пересмотра документа"),
                    ("DOCUMENT_VERSION_RETURNED", "Версия документа возвращена"),
                    ("DOCUMENT_UPDATED", "Новая версия документа"),
                ],
                max_length=40,
                verbose_name="Тип события",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("ACT", "Акт"),
                    ("PROTOCOL", "Протокол"),
                    ("TASK", "Задача"),
                    ("BUG", "Сообщение об ошибке"),
                    ("DOCUMENT", "Документ"),
                    ("REQUEST", "Заявка"),
                ],
                default="ACT",
                max_length=16,
                verbose_name="Тип источника",
            ),
        ),
    ]
