"""The bug report table.

One model, and no reference data to seed: who *receives* a report is
`accounts.UserProfile.is_bug_responsible` (`accounts.0009`), a flag on the
profile rather than a row here.
"""

# Generated by Django 6.0.6 on 2026-09-04 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Описание проблемы')),
                ('page_url', models.CharField(blank=True, max_length=500, verbose_name='Страница')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bug_reports', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Сообщение об ошибке',
                'verbose_name_plural': 'Сообщения об ошибках',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
